In [4]:
#packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from functools import reduce
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)
from functools import reduce
pd.options.mode.chained_assignment = None  # default='warn'
from warnings import simplefilter
simplefilter(action="ignore", category=pd.errors.PerformanceWarning)
import sys
sys.path.append("../../../Functions and Dictionaries/") # Adds higher directory to python modules path
import geodict
namestocommon = geodict.namestocommon
geotogeoid = geodict.geotogeoid
tofullcensus = geodict.tofullcensus
import sqlite3 as sq

import pandas as pd
import geopandas as gpd

In [6]:
data = gpd.read_file('../../Data Downloads/SHP/WalkabilityIndex_TN.shp')

In [7]:
data.head()

,OBJECTID,GEOID10,GEOID20,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,CSA,CSA_Name,CBSA,CBSA_Name,Ac_Total,Ac_Water,Ac_Land,Ac_Unpr,TotPop,CountHU,HH,Workers,D2B_E8MIXA,D2A_EPHHM,D3B,D4A,D2A_Ranked,D2B_Ranked,D3B_Ranked,D4A_Ranked,NatWalkInd,Shape_Leng,Shape_Area,geometry
0,200129,471251001001,471251001001,47,125,100100,1,None,None,17300,"Clarksville, TN-KY",318.283332,19.143331,299.140001,299.140000,1148,544,387,401,0.833326,0.854514,153.367653,-99999.0,20.0,20.0,18.0,1.0,13.000000,4829.941027,1.288074e+06,"POLYGON ((764970.018 1532779.791, 765054.475 1..."
1,200130,471251002001,471251002001,47,125,100200,1,None,None,17300,"Clarksville, TN-KY",173.360665,0.000000,173.360665,161.788770,414,336,212,249,0.773832,0.558841,118.168444,-99999.0,12.0,18.0,16.0,1.0,10.666667,4642.534449,7.015799e+05,"POLYGON ((765228.189 1531972.272, 765223.675 1..."
2,200131,471251002002,471251002002,47,125,100200,2,None,None,17300,"Clarksville, TN-KY",506.449982,48.518332,457.931650,456.777410,1080,589,482,347,0.654278,0.704999,70.375568,-99999.0,16.0,14.0,11.0,1.0,9.000000,7197.832631,2.049578e+06,"POLYGON ((764076.179 1529727.370, 764177.431 1..."
3,200132,471119702002,471119702002,47,111,970200,2,400,"Nashville-Davidson--Murfreesboro, TN",34980,"Nashville-Davidson--Murfreesboro--Franklin, TN",14586.019198,0.000000,14586.019198,14586.019198,1705,800,737,934,0.156332,0.118930,2.824184,-99999.0,2.0,2.0,3.0,1.0,2.000000,34253.467212,5.902881e+07,"POLYGON ((875968.173 1555468.583, 875971.250 1..."
4,200133,471251003001,471251003001,47,125,100300,1,None,None,17300,"Clarksville, TN-KY",508.783842,0.000000,508.783842,508.783842,1277,549,535,537,0.587312,0.461127,39.850322,-99999.0,9.0,11.0,8.0,1.0,6.333333,7814.735482,2.059019e+06,"POLYGON ((765135.941 1530415.848, 765152.111 1..."