###### Imports and Settings

In [1]:
import pandas as pd
import numpy as np
import requests
import pickle
from collections import deque
from functools import reduce
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)
from warnings import simplefilter
simplefilter(action="ignore", category=pd.errors.PerformanceWarning)
pd.options.mode.chained_assignment = None  # default='warn'

In [2]:
import sys
sys.path.append("../../../Functions and Dictionaries") # Adds higher directory to python modules path
import geodict
GNRC = geodict.GNRC
KY = geodict.KY
censusplaces = geodict.censusplaces

# American Community Survey 2022 1 Year Estimates

In [3]:
#read in API key
with open('api_keys.pkl', 'rb') as keys_file:
        keys_dict_2 = pickle.load(keys_file)

In [4]:
#variable containing Census API key
api_key = keys_dict_2['CENSUS']

## Read In Data Guide

In [6]:
dataguide = pd.read_csv('../../Data Guides/DATA GUIDE ACS 2022 5YR.csv', dtype = str)
dataguide['ID'] = dataguide['ID'].astype(int)

In [7]:
dg1 = dataguide[dataguide['ID'].between(1, 46)]
dg2 = dataguide[dataguide['ID'].between(47, 92)]
dg3 = dataguide[dataguide['ID'].between(93, 138)]
dg4 = dataguide[dataguide['ID'].between(139, 184)]
dg5 = dataguide[dataguide['ID'].between(185, 230)]
dg6 = dataguide[dataguide['ID'].between(231, 276)]
dg7 = dataguide[dataguide['ID'].between(277, 322)]
dg8 = dataguide[dataguide['ID'].between(323, 368)]
dg9 = dataguide[dataguide['ID'].between(369, 414)]
dg10 = dataguide[dataguide['ID'].between(415, 460)]
dg11 = dataguide[dataguide['ID'].between(461, 506)]
dg12 = dataguide[dataguide['ID'].between(507, 552)]
dg13 = dataguide[dataguide['ID'].between(553, 598)]
dg14 = dataguide[dataguide['ID'].between(599, 644)]
dg15 = dataguide[dataguide['ID'].between(645, 690)]
dg16 = dataguide[dataguide['ID'].between(691, 736)]
dg17 = dataguide[dataguide['ID'].between(737, 782)]
dg18 = dataguide[dataguide['ID'].between(783, 828)]
dg19 = dataguide[dataguide['ID'].between(829, 874)]
dg20 = dataguide[dataguide['ID'].between(875, 920)]
dg21 = dataguide[dataguide['ID'].between(921, 966)]
dg22 = dataguide[dataguide['ID'].between(967, 1012)]
dg23 = dataguide[dataguide['ID'].between(1013, 1058)]
dg24 = dataguide[dataguide['ID'].between(1059, 1104)]
dg25 = dataguide[dataguide['ID'].between(1105, 1150)]
dg26 = dataguide[dataguide['ID'].between(1151, 1196)]
dg27 = dataguide[dataguide['ID'].between(1197, 1242)]
dg28 = dataguide[dataguide['ID'].between(1243, 1287)]
dg29 = dataguide[dataguide['ID'].between(1288, 1332)]
dg30 = dataguide[dataguide['ID'].between(1333, 1377)]
dg31 = dataguide[dataguide['ID'].between(1378, 1422)]
dg32 = dataguide[dataguide['ID'].between(1423, 1467)]
dg33 = dataguide[dataguide['ID'].between(1468, 1512)]
dg34 = dataguide[dataguide['ID'].between(1513, 1557)]
dg35 = dataguide[dataguide['ID'].between(1558, 1602)]
dg36 = dataguide[dataguide['ID'].between(1603, 1647)]
dg37 = dataguide[dataguide['ID'].between(1648, 1692)]
dg38 = dataguide[dataguide['ID'].between(1693, 1737)]
dg39 = dataguide[dataguide['ID'].between(1738, 1782)]
dg40 = dataguide[dataguide['ID'].between(1783, 1827)]
dg41 = dataguide[dataguide['ID'].between(1828, 1872)]
dg42 = dataguide[dataguide['ID'].between(1873, 1917)]
dg43 = dataguide[dataguide['ID'].between(1918, 1962)]
dg44 = dataguide[dataguide['ID'].between(1963, 2007)]
dg45 = dataguide[dataguide['ID'].between(2008, 2052)]
dg46 = dataguide[dataguide['ID'].between(2053, 2097)]
dg47 = dataguide[dataguide['ID'].between(2098, 2142)]
dg48 = dataguide[dataguide['ID'].between(2143, 2187)]
dg49 = dataguide[dataguide['ID'].between(2188, 2232)]
dg50 = dataguide[dataguide['ID'].between(2233, 2277)]
dg51 = dataguide[dataguide['ID'].between(2278, 2322)]
dg52 = dataguide[dataguide['ID'].between(2323, 2367)]
dg53 = dataguide[dataguide['ID'].between(2368, 2412)]
dg54 = dataguide[dataguide['ID'].between(2413, 2457)]
dg55 = dataguide[dataguide['ID'].between(2458, 2502)]
dg56 = dataguide[dataguide['ID'].between(2503, 2547)]
dg57 = dataguide[dataguide['ID'].between(2548, 2592)]
dg58 = dataguide[dataguide['ID'].between(2593, 2637)]
dg59 = dataguide[dataguide['ID'].between(2638, 2682)]
dg60 = dataguide[dataguide['ID'].between(2683, 2727)]
dg61 = dataguide[dataguide['ID'].between(2728, 2772)]
dg62 = dataguide[dataguide['ID'].between(2773, 2817)]
dg63 = dataguide[dataguide['ID'].between(2818, 2862)]
dg64 = dataguide[dataguide['ID'].between(2863, 2907)]
dg65 = dataguide[dataguide['ID'].between(2908, 2952)]
dg66 = dataguide[dataguide['ID'].between(2953, 2997)]
dg67 = dataguide[dataguide['ID'].between(2998, 3042)]
dg68 = dataguide[dataguide['ID'].between(3043, 3086)]
dg69 = dataguide[dataguide['ID'].between(3087, 3131)]
dg70 = dataguide[dataguide['ID'].between(3132, 3176)]
dg71 = dataguide[dataguide['ID'].between(3177, 3221)]
dg72 = dataguide[dataguide['ID'].between(3222, 3266)]
dg73 = dataguide[dataguide['ID'].between(3267, 3311)]
dg74 = dataguide[dataguide['ID'].between(3312, 3356)]
dg75 = dataguide[dataguide['ID'].between(3357, 3401)]

In [8]:
dfs = [dg1, dg2, dg3, dg4, dg5, dg6, dg7, dg8, dg9, dg10, dg11, dg12, dg13, dg14, dg15, dg16, dg17, dg18, dg19, dg20, dg21, dg22, dg23, dg24, dg25, 
       dg26, dg27, dg28, dg29, dg30, dg31, dg32, dg33, dg34, dg35, dg36, dg37, dg38, dg39, dg40, dg41, dg42, dg43, dg44, dg45, dg46, dg47, dg48, dg49,
       dg50, dg51, dg52, dg53, dg54, dg55, dg56, dg57, dg58, dg59, dg60, dg61, dg62, dg63, dg64, dg65, dg66, dg67, dg68, dg69, dg70, dg71, dg72, dg73, dg74, dg75]

In [9]:
droppers = ['ID', 'Data Point']
for df in dfs:
    df.drop(droppers, axis = 1, inplace = True)

In [10]:
#url string and list parameters for column head and tail
url_str= 'https://api.census.gov/data/2022/acs/acs1?key='+api_key
head1 = 'NAME' 
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'

In [11]:
results = []
for df in dfs:
    dataguide = df
    for col_name, col_data in df.items():
        var_list = list(dataguide['Variable']) #make variables list
        var_list = deque(var_list)
        var_list.appendleft(head2)
        var_list.appendleft(head1)
        col_list = list(dataguide['Column Name']) #make columns list
        col_list.append(tail_cols1)
        col_list.append(tail_cols2)
        col_list = deque(col_list)
        col_list.appendleft(head2)
        col_list.appendleft(head1)
        predicates= {} #call for all counties in state of TN
        get_vars= var_list
        predicates["get"]= ",". join(get_vars)
        predicates["for"]= "county:*"
        predicates["in"]= "state:47"                                                             
        data = requests.get(url_str, params= predicates)                                                                
        col_names = col_list
        df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
        predicates= {} #call for all counties in state of KY
        get_vars= var_list
        predicates["get"]= ",". join(get_vars)
        predicates["for"]= "county:*"
        predicates["in"]= "state:21"                                                             
        data = requests.get(url_str, params= predicates)                                                                
        col_names = col_list
        kycos = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
        kycos = kycos.loc[kycos['GeoFIPS'].isin(KY)] #filter for counties of concern in KY
        df = pd.concat([df, kycos], axis = 0)
        col_list.remove(tail_cols2) #adjust the column list for different formats of geos 
        predicates= {} #call for state of TN
        get_vars= var_list
        predicates["get"]= ",". join(get_vars)
        predicates["for"]= "state:47"
        data= requests.get(url_str, params= predicates)
        col_names = col_list
        state = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
        state['GeoFIPS'] = '0' #fill in the blank GeoFIPS column
        df = pd.concat([df, state], axis = 0)
        predicates = {} #call for US
        get_vars = var_list
        predicates["get"] = ",". join(get_vars)
        predicates["for"] = "us:*"
        data = requests.get(url_str, params= predicates)
        col_names = col_list
        national = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
        national['GeoFIPS'] = '0' #fill in the blank GeoFIPS column
        df = pd.concat([df, national], axis = 0)
        results.append(df)
new_df = pd.concat(results, axis = 1)
new_df = new_df.transpose().reset_index(drop = False).drop_duplicates()
new_df.columns = new_df.iloc[0]
new_df = new_df.set_index('NAME').transpose().drop(columns = ['StateFIPS', 'GeoFIPS']).reset_index(drop = True)
new_df = new_df.rename_axis(None, axis = 1)
print('Okay Finished')

Okay Finished

In [13]:
new_df.head()

                         NAME          GEO_ID agebysex_total_series age_total_male age_m_u5 age_m_5to9 age_m_10to14 age_m_15to17 age_m_18to19  \
0  Anderson County, Tennessee  0500000US47001                 78913          39237     2233       2311         2276         1718          867
1    Blount County, Tennessee  0500000US47009                139958          68650     3687       3635         4657         2803          856
2   Bradley County, Tennessee  0500000US47011                110616          53527     2867       3739         3270         2322         1720
3  Davidson County, Tennessee  0500000US47037                708144         341794    22544      19758        17648        10806         8274
4    Greene County, Tennessee  0500000US47059                 71405          35669     1585       1804         2456         1325         1200

  age_m_20 age_m_21 age_m_22to24 age_m_25to29 age_m_30to34 age_m_35to39 age_m_40to44 age_m_45to49 age_m_50to54 age_m_55to59 age_m_60to61  \
0      322      118         2014         2435         2829         2109         2553         2109         2741         2522         1346
1      447      853         2829         4332         4353         2980         5155         3933         5085         5052         2065
2      472     1292         1531         2991         4211         3730         2735         3552         3828         3158         1430
3     3653     4775        16024        34536        35400        31279        20560        19834        19318        18186         8543
4      692      416         1169         2235         1942         1728         2091         2140         2385         2336          446

  age_m_62to64 age_m_65to66 age_m_67to69 age_m_70to74 age_m_75to79 age_m_80to84 age_m_85+ age_total_female age_f_u5 age_f_5to9 age_f_10to14  \
0         1616          624         1441         2167         1283          822       781            39676     1758       2075         2571
1         2716         1890         2273         3766         2662         1483      1138            71308     3315       3970         3121
2         2438         1313         1538         2237         1411         1161       581            57089     2999       3786         3039
3        10058         5939         8192        12622         7652         2998      3195           366350    22336      18249        18382
4         2520         1570         1033         1624         1639          854       479            35736     1874       1413         1695

  age_f_15to17 age_f_18to19 age_f_20 age_f_21 age_f_22to24 age_f_25to29 age_f_30to34 age_f_35to39 age_f_40to44 age_f_45to49 age_f_50to54  \
0         1570          784       91      242         2118         2339         2375         1919         2502         2442         2786
1         2486         1197     1811      484         1562         4527         4200         4019         4439         3970         5035
2         1797         1577      592      634         2785         3345         3876         2751         3659         3547         3977
3        10816         8767     5620     4256        18174        37783        36474        26467        24564        19343        20272
4         1202          756      450      400         1200         2080         2072         2028         2018         2116         2338

  age_f_55to59 age_f_60to61 age_f_62to64 age_f_65to66 age_f_67to69 age_f_70to74 age_f_75to79 age_f_80to84 age_f_85+ raceeth_white_alone  \
0         3193          944         1594          875         1492         2333         1896          841       936               69106
1         4566         2498         3495         2786         2866         4207         3015         2012      1727              125214
2         3714         2249         1677         2096         1651         2650         1806         1579      1303               94309
3        19376         7604        13980         8047        10212        13702        10008         5776      6142              401293
4         3221          669         1695          944         1084         2868         2077         1151       385               65710

  raceeth_blackafricanamerican_alone raceeth_americanindianalaskanative_alone raceeth_asian_alone raceeth_nativehawaiianotherpacificislander_alone  \
0                               None                                     None                None                                             None
1                               None                                     None                None                                             None
2                               None                                     None                None                                             None
3                             178312                                     None               25145                                             None
4                               None                                     None                None                                             None

  raceeth_someotherrace_alone raceeth_twoormoreraces_alone raceeth_whitealone_nothispanicorlatino raceeth_hispanicorlatino hhsize_avg  \
0                        None                         None                                  68299                     None       2.42
1                        None                         None                                 124833                     None       2.45
2                        None                         None                                  92590                     8200       2.57
3                       22244                        79615                                 393994                    77518       2.10
4                        None                         None                                  65487                     None       2.39

  healthcoverage_total_healthcare_series healthcoverage_total_mallhealthcare healthcoverage_mu6_all healthcoverage_mu6_w healthcoverage_mu6_wo  \
0                                  77811                               38540                   2631                 2631                     0
1                                 138621                               67948                   4008                 3587                   421
2                                 109697                               53086                   3305                 3173                   132
3                                 703265                              339387                  25936                24050                  1886
4                                  70636                               35110                   2014                 1985                    29

  healthcoverage_m6to18_all healthcoverage_m6to18_w healthcoverage_m6to18_wo healthcoverage_m19to25_all healthcoverage_m19to25_w  \
0                      6487                    6487                        0                       3224                     2570
1                     11299                   10847                      452                       5129                     4492
2                      9634                    9204                      430                       4738                     4143
3                     49885                   46525                     3360                      33740                    25856
4                      5725                    5591                      134                       3300                     2857

  healthcoverage_m19to25_wo healthcoverage_m26to34_all healthcoverage_m26to34_w healthcoverage_m26to34_wo healthcoverage_m35to44_all  \
0                       654                       4466                     3343                      1123                       4488
1                       637                       7684                     5254                      2430                       7989
2                       595                       6628                     5036                      1592                       6219
3                      7884                      63142                    52651                     10491                      51351
4                       443                       3572                     2189                      1383                       3748

  healthcoverage_m35to44_w healthcoverage_m35to44_wo healthcoverage_m45to54_all healthcoverage_m45to54_w healthcoverage_m45to54_wo  \
0                     3391                      1097                       4815                     4449                       366
1                     6326                      1663                       8979                     8411                       568
2                     4763                      1456                       7308                     6892                       416
3                    42796                      8555                      38642                    32424                      6218
4                     3327                       421                       4494                     3734                       760

  healthcoverage_m55to64_all healthcoverage_m55to64_w healthcoverage_m55to64_wo healthcoverage_m65to74_all healthcoverage_m65to74_w  \
0                       5415                     4919                       496                       4179                     4179
1                       9833                     8215                      1618                       7871                     7871
2                       7026                     6332                       694                       5088                     5088
3                      36595                    32547                      4048                      26449                    25585
4                       5302                     4457                       845                       4184                     4083

  healthcoverage_m65to74_wo healthcoverage_m75+_all healthcoverage_m75+_w healthcoverage_m75+_wo healthcoverage_total_fallhealthcare  \
0                         0                    2835                  2835                      0                               39271
1                         0                    5156                  5156                      0                               70673
2                         0                    3140                  3140                      0                               56611
3                       864                   13647                 13343                    304                              363878
4                       101                    2771                  2771                      0                               35526

  healthcoverage_fu6_all healthcoverage_fu6_w healthcoverage_fu6_wo healthcoverage_f6to18_all healthcoverage_f6to18_w healthcoverage_f6to18_wo  \
0                   1883                 1883                     0                      6293                    6201                       92
1                   4341                 4056                   285                      9127                    8575                      552
2                   3617                 3329                   288                      8835                    8003                      832
3                  26727                25854                   873                     47069                   41948                     5121
4                   2375                 2185                   190                      4049                    3913                      136

  healthcoverage_f19to25_all healthcoverage_f19to25_w healthcoverage_f19to25_wo healthcoverage_f26to34_all healthcoverage_f26to34_w  \
0                       3867                     3129                       738                       3845                     3554
1                       5375                     4551                       824                       7708                     6584
2                       5494                     5122                       372                       6435                     5668
3                      40081                    35119                      4962                      66167                    55998
4                       3456                     3031                       425                       3198                     2910

  healthcoverage_f26to34_wo healthcoverage_f35to44_all healthcoverage_f35to44_w healthcoverage_f35to44_wo healthcoverage_f45to54_all  \
0                       291                       4317                     4109                       208                       5185
1                      1124                       8289                     7132                      1157                       8968
2                       767                       6410                     5830                       580                       7512
3                     10169                      50761                    43224                      7537                      39599
4                       288                       3991                     3695                       296                       4454

  healthcoverage_f45to54_w healthcoverage_f45to54_wo healthcoverage_f55to64_all healthcoverage_f55to64_w healthcoverage_f55to64_wo  \
0                     4221                       964                       5731                     5232                       499
1                     8358                       610                      10559                     9204                      1355
2                     6309                      1203                       7591                     6731                       860
3                    35800                      3799                      40865                    36579                      4286
4                     3722                       732                       5585                     4605                       980

  healthcoverage_f65to74_all healthcoverage_f65to74_w healthcoverage_f65to74_wo healthcoverage_f75+_all healthcoverage_f75+_w  \
0                       4700                     4700                         0                    3450                  3450
1                       9859                     9606                       253                    6447                  6447
2                       6116                     6116                         0                    4601                  4601
3                      31503                    31153                       350                   21106                 21023
4                       4889                     4889                         0                    3529                  3529

  healthcoverage_f75+_wo healthcoverage_total_privatehealthcare_series healthcoverage_total_mprivate healthcoverage_mu6_privateall  \
0                      0                                         77811                         38540                          2631
1                      0                                        138621                         67948                          4008
2                      0                                        109697                         53086                          3305
3                     83                                        703265                        339387                         25936
4                      0                                         70636                         35110                          2014

  healthcoverage_mu6_wprivate healthcoverage_mu6_woprivate healthcoverage_m6to18_privateall healthcoverage_m6to18_wprivate  \
0                        1621                         1010                             6487                           4534
1                        2219                         1789                            11299                           7631
2                        1849                         1456                             9634                           6283
3                       15899                        10037                            49885                          29185
4                         673                         1341                             5725                           3856

  healthcoverage_m6to18_woprivate healthcoverage_m19to25_privateall healthcoverage_m19to25_wprivate healthcoverage_m19to25_woprivate  \
0                            1953                              3224                            2322                              902
1                            3668                              5129                            3887                             1242
2                            3351                              4738                            3792                              946
3                           20700                             33740                           24229                             9511
4                            1869                              3300                            2123                             1177

  healthcoverage_m26to34_privateall healthcoverage_m26to34_wprivate healthcoverage_m26to34_woprivate healthcoverage_m35to44_privateall  \
0                              4466                            2860                             1606                              4488
1                              7684                            4899                             2785                              7989
2                              6628                            4521                             2107                              6219
3                             63142                           49981                            13161                             51351
4                              3572                            1862                             1710                              3748

  healthcoverage_m35to44_wprivate healthcoverage_m35to44_woprivate healthcoverage_m45to54_privateall healthcoverage_m45to54_wprivate  \
0                            2973                             1515                              4815                            3642
1                            5495                             2494                              8979                            7529
2                            4557                             1662                              7308                            6731
3                           40810                            10541                             38642                           30074
4                            3156                              592                              4494                            3433

  healthcoverage_m45to54_woprivate healthcoverage_m55to64_privateall healthcoverage_m55to64_wprivate healthcoverage_m55to64_woprivate  \
0                             1173                              5415                            3575                             1840
1                             1450                              9833                            6734                             3099
2                              577                              7026                            5431                             1595
3                             8568                             36595                           29897                             6698
4                             1061                              5302                            3105                             2197

  healthcoverage_m65to74_privateall healthcoverage_m65to74_wprivate healthcoverage_m65to74_woprivate healthcoverage_m75+_privateall  \
0                              4179                            1759                             2420                           2835
1                              7871                            4488                             3383                           5156
2                              5088                            2833                             2255                           3140

In [14]:
data = new_df

In [15]:
data['NAME'].unique()

array(['Anderson County, Tennessee', 'Blount County, Tennessee',
       'Bradley County, Tennessee', 'Davidson County, Tennessee',
       'Greene County, Tennessee', 'Hamblen County, Tennessee',
       'Hamilton County, Tennessee', 'Knox County, Tennessee',
       'Madison County, Tennessee', 'Maury County, Tennessee',
       'Montgomery County, Tennessee', 'Putnam County, Tennessee',
       'Robertson County, Tennessee', 'Rutherford County, Tennessee',
       'Sevier County, Tennessee', 'Shelby County, Tennessee',
       'Sullivan County, Tennessee', 'Sumner County, Tennessee',
       'Washington County, Tennessee', 'Williamson County, Tennessee',
       'Wilson County, Tennessee', 'Christian County, Kentucky',
       'Tennessee', 'United States'], dtype=object)

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Columns: 3359 entries, NAME to transpo_workedfromhome_bgequiv
dtypes: object(3359)
memory usage: 629.9+ KB

In [17]:
data.to_feather('../../Raw Data/ACS20221YR')

In [18]:
data.to_csv('../../Raw Data/ACS20221YR.csv')