###### Imports and Settings

In [1]:
import pandas as pd
import numpy as np
import requests
import pickle
from collections import deque
from functools import reduce
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)
from warnings import simplefilter
simplefilter(action="ignore", category=pd.errors.PerformanceWarning)
pd.options.mode.chained_assignment = None  # default='warn'

In [2]:
import sys
sys.path.append("../../../Functions and Dictionaries") # Adds higher directory to python modules path
import geodict
GNRC = geodict.GNRC
KY = geodict.KY
censusplaces = geodict.censusplaces

# American Community Survey 2021 1 Year Estimates

In [3]:
#read in API key
with open('api_keys.pkl', 'rb') as keys_file:
        keys_dict_2 = pickle.load(keys_file)

In [4]:
#variable containing Census API key
api_key = keys_dict_2['CENSUS']

## Read In Data Guide

In [13]:
dataguide = pd.read_csv('../../Data Guides/DATA GUIDE ACS 2020_2021 5YR.csv', dtype = str)
dataguide['ID'] = dataguide['ID'].astype(int)

In [14]:
dg1 = dataguide[dataguide['ID'].between(1, 46)]
dg2 = dataguide[dataguide['ID'].between(47, 92)]
dg3 = dataguide[dataguide['ID'].between(93, 138)]
dg4 = dataguide[dataguide['ID'].between(139, 184)]
dg5 = dataguide[dataguide['ID'].between(185, 230)]
dg6 = dataguide[dataguide['ID'].between(231, 276)]
dg7 = dataguide[dataguide['ID'].between(277, 322)]
dg8 = dataguide[dataguide['ID'].between(323, 368)]
dg9 = dataguide[dataguide['ID'].between(369, 414)]
dg10 = dataguide[dataguide['ID'].between(415, 460)]
dg11 = dataguide[dataguide['ID'].between(461, 506)]
dg12 = dataguide[dataguide['ID'].between(507, 552)]
dg13 = dataguide[dataguide['ID'].between(553, 598)]
dg14 = dataguide[dataguide['ID'].between(599, 644)]
dg15 = dataguide[dataguide['ID'].between(645, 690)]
dg16 = dataguide[dataguide['ID'].between(691, 736)]
dg17 = dataguide[dataguide['ID'].between(737, 782)]
dg18 = dataguide[dataguide['ID'].between(783, 828)]
dg19 = dataguide[dataguide['ID'].between(829, 874)]
dg20 = dataguide[dataguide['ID'].between(875, 920)]
dg21 = dataguide[dataguide['ID'].between(921, 966)]
dg22 = dataguide[dataguide['ID'].between(967, 1012)]
dg23 = dataguide[dataguide['ID'].between(1013, 1058)]
dg24 = dataguide[dataguide['ID'].between(1059, 1104)]
dg25 = dataguide[dataguide['ID'].between(1105, 1150)]
dg26 = dataguide[dataguide['ID'].between(1151, 1196)]
dg27 = dataguide[dataguide['ID'].between(1197, 1242)]
dg28 = dataguide[dataguide['ID'].between(1243, 1287)]
dg29 = dataguide[dataguide['ID'].between(1288, 1332)]
dg30 = dataguide[dataguide['ID'].between(1333, 1377)]
dg31 = dataguide[dataguide['ID'].between(1378, 1422)]
dg32 = dataguide[dataguide['ID'].between(1423, 1467)]
dg33 = dataguide[dataguide['ID'].between(1468, 1512)]
dg34 = dataguide[dataguide['ID'].between(1513, 1557)]
dg35 = dataguide[dataguide['ID'].between(1558, 1602)]
dg36 = dataguide[dataguide['ID'].between(1603, 1647)]
dg37 = dataguide[dataguide['ID'].between(1648, 1692)]
dg38 = dataguide[dataguide['ID'].between(1693, 1737)]
dg39 = dataguide[dataguide['ID'].between(1738, 1782)]
dg40 = dataguide[dataguide['ID'].between(1783, 1827)]
dg41 = dataguide[dataguide['ID'].between(1828, 1872)]
dg42 = dataguide[dataguide['ID'].between(1873, 1917)]
dg43 = dataguide[dataguide['ID'].between(1918, 1962)]
dg44 = dataguide[dataguide['ID'].between(1963, 2007)]
dg45 = dataguide[dataguide['ID'].between(2008, 2052)]
dg46 = dataguide[dataguide['ID'].between(2053, 2097)]
dg47 = dataguide[dataguide['ID'].between(2098, 2142)]
dg48 = dataguide[dataguide['ID'].between(2143, 2187)]
dg49 = dataguide[dataguide['ID'].between(2188, 2232)]
dg50 = dataguide[dataguide['ID'].between(2233, 2277)]
dg51 = dataguide[dataguide['ID'].between(2278, 2322)]
dg52 = dataguide[dataguide['ID'].between(2323, 2367)]
dg53 = dataguide[dataguide['ID'].between(2368, 2412)]
dg54 = dataguide[dataguide['ID'].between(2413, 2457)]
dg55 = dataguide[dataguide['ID'].between(2458, 2502)]
dg56 = dataguide[dataguide['ID'].between(2503, 2547)]
dg57 = dataguide[dataguide['ID'].between(2548, 2592)]
dg58 = dataguide[dataguide['ID'].between(2593, 2637)]
dg59 = dataguide[dataguide['ID'].between(2638, 2682)]
dg60 = dataguide[dataguide['ID'].between(2683, 2727)]
dg61 = dataguide[dataguide['ID'].between(2728, 2772)]
dg62 = dataguide[dataguide['ID'].between(2773, 2817)]
dg63 = dataguide[dataguide['ID'].between(2818, 2862)]
dg64 = dataguide[dataguide['ID'].between(2863, 2907)]
dg65 = dataguide[dataguide['ID'].between(2908, 2952)]
dg66 = dataguide[dataguide['ID'].between(2953, 2997)]
dg67 = dataguide[dataguide['ID'].between(2998, 3042)]
dg68 = dataguide[dataguide['ID'].between(3043, 3086)]
dg69 = dataguide[dataguide['ID'].between(3087, 3131)]
dg70 = dataguide[dataguide['ID'].between(3132, 3176)]
dg71 = dataguide[dataguide['ID'].between(3177, 3221)]
dg72 = dataguide[dataguide['ID'].between(3222, 3266)]
dg73 = dataguide[dataguide['ID'].between(3267, 3311)]

In [15]:
dfs = [dg1, dg2, dg3, dg4, dg5, dg6, dg7, dg8, dg9, dg10, dg11, dg12, dg13, dg14, dg15, dg16, dg17, dg18, dg19, dg20, dg21, dg22, dg23, dg24, dg25, 
       dg26, dg27, dg28, dg29, dg30, dg31, dg32, dg33, dg34, dg35, dg36, dg37, dg38, dg39, dg40, dg41, dg42, dg43, dg44, dg45, dg46, dg47, dg48, dg49,
       dg50, dg51, dg52, dg53, dg54, dg55, dg56, dg57, dg58, dg59, dg60, dg61, dg62, dg63, dg64, dg65, dg66, dg67, dg68, dg69, dg70, dg71, dg72, dg73]

In [16]:
droppers = ['ID', 'Data Point']
for df in dfs:
    df.drop(droppers, axis = 1, inplace = True)

In [17]:
# droppers = ['ID', 'Data Point']
# for df in dfs1:
#     df.drop(droppers, axis = 1, inplace = True)

In [18]:
#url string and list parameters for column head and tail
url_str= 'https://api.census.gov/data/2021/acs/acs1?key='+api_key
head1 = 'NAME' 
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'

In [19]:
results = []
for df in dfs:
    dataguide = df
    for col_name, col_data in df.items():
        var_list = list(dataguide['Variable']) #make variables list
        var_list = deque(var_list)
        var_list.appendleft(head2)
        var_list.appendleft(head1)
        col_list = list(dataguide['Column Name']) #make columns list
        col_list.append(tail_cols1)
        col_list.append(tail_cols2)
        col_list = deque(col_list)
        col_list.appendleft(head2)
        col_list.appendleft(head1)
        predicates= {} #call for all counties in state of TN
        get_vars= var_list
        predicates["get"]= ",". join(get_vars)
        predicates["for"]= "county:*"
        predicates["in"]= "state:47"                                                             
        data = requests.get(url_str, params= predicates)                                                                
        col_names = col_list
        df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
        predicates= {} #call for all counties in state of KY
        get_vars= var_list
        predicates["get"]= ",". join(get_vars)
        predicates["for"]= "county:*"
        predicates["in"]= "state:21"                                                             
        data = requests.get(url_str, params= predicates)                                                                
        col_names = col_list
        kycos = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
        kycos = kycos.loc[kycos['GeoFIPS'].isin(KY)] #filter for counties of concern in KY
        df = pd.concat([df, kycos], axis = 0)
        col_list.remove(tail_cols2) #adjust the column list for different formats of geos 
        predicates= {} #call for state of TN
        get_vars= var_list
        predicates["get"]= ",". join(get_vars)
        predicates["for"]= "state:47"
        data= requests.get(url_str, params= predicates)
        col_names = col_list
        state = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
        state['GeoFIPS'] = '0' #fill in the blank GeoFIPS column
        df = pd.concat([df, state], axis = 0)
        predicates = {} #call for US
        get_vars = var_list
        predicates["get"] = ",". join(get_vars)
        predicates["for"] = "us:*"
        data = requests.get(url_str, params= predicates)
        col_names = col_list
        national = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
        national['GeoFIPS'] = '0' #fill in the blank GeoFIPS column
        df = pd.concat([df, national], axis = 0)
        results.append(df)
new_df = pd.concat(results, axis = 1)
new_df = new_df.transpose().reset_index(drop = False).drop_duplicates()
new_df.columns = new_df.iloc[0]
new_df = new_df.set_index('NAME').transpose().drop(columns = ['StateFIPS', 'GeoFIPS']).reset_index(drop = True)
new_df = new_df.rename_axis(None, axis = 1)
print('Okay Finished')

Okay Finished

In [20]:
new_df.head()

                           NAME          GEO_ID agebysex_total_series age_total_male age_m_u5 age_m_5to9 age_m_10to14 age_m_15to17 age_m_18to19  \
0    Anderson County, Tennessee  0500000US47001                 77576          38441     1798       3105         2166         1540          884
1    Hamilton County, Tennessee  0500000US47065                369135         178895    10836      11731        10297         6625         5154
2        Knox County, Tennessee  0500000US47093                486677         237254    13182      13092        16209         8994         7534
3  Rutherford County, Tennessee  0500000US47149                352182         174964    11215      13891        11180         8844         4490
4      Sevier County, Tennessee  0500000US47155                 99517          49578     2503       3280         3484         1642         1580

  age_m_20 age_m_21 age_m_22to24 age_m_25to29 age_m_30to34 age_m_35to39 age_m_40to44 age_m_45to49 age_m_50to54 age_m_55to59 age_m_60to61  \
0      764      398         1180         2658         2565         2799         1528         2183         2250         3124         1373
1     2397     2776         7173        10704        11904        13632        11050        10913        11269        11343         4244
2     5164     4675        10883        17536        16122        15963        14858        13939        15215        15015         5441
3     3031     3312         8469        14491        11461        13538        11381        11991        11179         9152         3442
4      551      477         1585         3346         2890         2758         2616         3079         3223         3281         1466

  age_m_62to64 age_m_65to66 age_m_67to69 age_m_70to74 age_m_75to79 age_m_80to84 age_m_85+ age_total_female age_f_u5 age_f_5to9 age_f_10to14  \
0          725          981         1204         2525         1174          456      1061            39135     2292       1816         2367
1         7809         4052         6378         7936         4527         2631      3514           190240    10190      10063        10868
2         8512         4837         6781        10861         6630         3563      2248           249423    13088      13850        14395
3         6499         2389         4260         5395         2358         1493      1503           177218    10677      12048        11951
4         2468         1278         1612         2992         1657         1268       542            49939     2277       2570         2923

  age_f_15to17 age_f_18to19 age_f_20 age_f_21 age_f_22to24 age_f_25to29 age_f_30to34 age_f_35to39 age_f_40to44 age_f_45to49 age_f_50to54  \
0         1337          430      355      758         1067         2307         2398         2920         1820         2395         2614
1         6151         4682     1931     1558         8029        13052        14231        13231        10479        11217        11811
2         8752         7667     4031     4336        11819        17087        17198        16626        15230        14355        15237
3         6593         5814     4002     2352         8634        12951        12563        14897        10741        11751        11051
4         1629          599      354      633         2188         2976         3135         3551         1922         3118         3492

  age_f_55to59 age_f_60to61 age_f_62to64 age_f_65to66 age_f_67to69 age_f_70to74 age_f_75to79 age_f_80to84 age_f_85+ raceeth_white_alone  \
0         3625          745         1198         1501         1283         2311         1313          796      1487               68047
1        10536         6409         7843         4916         7362         9509         6621         4742      4809              259462
2        14425         6628        10440         4410         9497        12396         7641         4722      5593              394413
3         9390         4196         5569         3455         5374         4934         3964         1701      2610              240667
4         3864         1071         2989         1400         2191         2890         1847         1510       810               86978

  raceeth_blackafricanamerican_alone raceeth_americanindianalaskanative_alone raceeth_asian_alone raceeth_nativehawaiianotherpacificislander_alone  \
0                               None                                     None                None                                             None
1                              68166                                     None                6523                                             None
2                              32954                                     None                9784                                             None
3                              51459                                     None                None                                             None
4                               None                                     None                None                                             None

  raceeth_someotherrace_alone raceeth_twoormoreraces_alone raceeth_whitealone_nothispanicorlatino raceeth_hispanicorlatino hhsize_avg  \
0                        None                         None                                  67729                     None       2.40
1                        9566                        24547                                 254807                    23700       2.36
2                        8004                        39968                                 391130                    23837       2.39
3                       16519                        29530                                 235356                    33414       2.85
4                        None                         None                                  86941                     None       2.69

  healthcoverage_total_healthcare_series healthcoverage_total_mallhealthcare healthcoverage_mu6_all healthcoverage_mu6_w healthcoverage_mu6_wo  \
0                                  76370                               37977                   2516                 2432                    84
1                                 365415                              176910                  12475                11873                   602
2                                 483561                              236046                  16440                15939                   501
3                                 350596                              173955                  14584                13958                   626
4                                  98552                               48809                   2853                 2853                     0

  healthcoverage_m6to18_all healthcoverage_m6to18_w healthcoverage_m6to18_wo healthcoverage_m19to25_all healthcoverage_m19to25_w  \
0                      6808                    6336                      472                       2951                     1964
1                     29553                   28150                     1403                      16908                    13765
2                     38267                   36860                     1407                      27624                    24438
3                     32911                   31616                     1295                      19506                    16791
4                      8722                    8066                      656                       3677                     3021

  healthcoverage_m19to25_wo healthcoverage_m26to34_all healthcoverage_m26to34_w healthcoverage_m26to34_wo healthcoverage_m35to44_all  \
0                       987                       4518                     3407                      1111                       4327
1                      3143                      19993                    16968                      3025                      24601
2                      3186                      30624                    25083                      5541                      30467
3                      2715                      22973                    18875                      4098                      24726
4                       656                       5588                     3681                      1907                       5273

  healthcoverage_m35to44_w healthcoverage_m35to44_wo healthcoverage_m45to54_all healthcoverage_m45to54_w healthcoverage_m45to54_wo  \
0                     3472                       855                       4433                     3899                       534
1                    19185                      5416                      21646                    18885                      2761
2                    24940                      5527                      28985                    25590                      3395
3                    21911                      2815                      23083                    21387                      1696
4                     3752                      1521                       6282                     4951                      1331

  healthcoverage_m55to64_all healthcoverage_m55to64_w healthcoverage_m55to64_wo healthcoverage_m65to74_all healthcoverage_m65to74_w  \
0                       5222                     4496                       726                       4529                     4268
1                      23209                    20843                      2366                      18068                    17838
2                      28816                    26495                      2321                      22470                    22042
3                      19011                    17960                      1051                      12029                    12029
4                       7150                     5579                      1571                       5882                     5882

  healthcoverage_m65to74_wo healthcoverage_m75+_all healthcoverage_m75+_w healthcoverage_m75+_wo healthcoverage_total_fallhealthcare  \
0                       261                    2673                  2673                      0                               38393
1                       230                   10457                 10457                      0                              188505
2                       428                   12353                 12353                      0                              247515
3                         0                    5132                  5132                      0                              176641
4                         0                    3382                  3382                      0                               49743

  healthcoverage_fu6_all healthcoverage_fu6_w healthcoverage_fu6_wo healthcoverage_f6to18_all healthcoverage_f6to18_w healthcoverage_f6to18_wo  \
0                   2736                 2557                   179                      5314                    4941                      373
1                  12121                12048                    73                     27464                   26583                      881
2                  16115                15970                   145                     37741                   37266                      475
3                  13556                13328                   228                     30314                   28743                     1571
4                   2984                 2956                    28                      6918                    6118                      800

  healthcoverage_f19to25_all healthcoverage_f19to25_w healthcoverage_f19to25_wo healthcoverage_f26to34_all healthcoverage_f26to34_w  \
0                       2376                     1916                       460                       4283                     3349
1                      17597                    14958                      2639                      23500                    19927
2                      27250                    24467                      2783                      30937                    27541
3                      19555                    18182                      1373                      24120                    21753
4                       3784                     3103                       681                       5562                     4232

  healthcoverage_f26to34_wo healthcoverage_f35to44_all healthcoverage_f35to44_w healthcoverage_f35to44_wo healthcoverage_f45to54_all  \
0                       934                       4740                     3512                      1228                       4994
1                      3573                      23545                    20563                      2982                      22989
2                      3396                      31746                    28070                      3676                      29528
3                      2367                      25583                    22796                      2787                      22792
4                      1330                       5423                     4059                      1364                       6610

  healthcoverage_f45to54_w healthcoverage_f45to54_wo healthcoverage_f55to64_all healthcoverage_f55to64_w healthcoverage_f55to64_wo  \
0                     4638                       356                       5553                     5352                       201
1                    20517                      2472                      24562                    21139                      3423
2                    26868                      2660                      31476                    28957                      2519
3                    20973                      1819                      19142                    17496                      1646
4                     5769                       841                       7924                     6650                      1274

  healthcoverage_f65to74_all healthcoverage_f65to74_w healthcoverage_f65to74_wo healthcoverage_f75+_all healthcoverage_f75+_w  \
0                       4962                     4962                         0                    3435                  3435
1                      21484                    21115                       369                   15243                 15032
2                      26094                    25871                       223                   16628                 16628
3                      13703                    13566                       137                    7876                  7876
4                       6472                     6472                         0                    4066                  3859

  healthcoverage_f75+_wo healthcoverage_total_privatehealthcare_series healthcoverage_total_mprivate healthcoverage_mu6_privateall  \
0                      0                                         76370                         37977                          2516
1                    211                                        365415                        176910                         12475
2                      0                                        483561                        236046                         16440
3                      0                                        350596                        173955                         14584
4                    207                                         98552                         48809                          2853

  healthcoverage_mu6_wprivate healthcoverage_mu6_woprivate healthcoverage_m6to18_privateall healthcoverage_m6to18_wprivate  \
0                        1951                          565                             6808                           4127
1                        6581                         5894                            29553                          19889
2                       10788                         5652                            38267                          25801
3                        9077                         5507                            32911                          22382
4                        1607                         1246                             8722                           3542

  healthcoverage_m6to18_woprivate healthcoverage_m19to25_privateall healthcoverage_m19to25_wprivate healthcoverage_m19to25_woprivate  \
0                            2681                              2951                            1873                             1078
1                            9664                             16908                           12956                             3952
2                           12466                             27624                           22801                             4823
3                           10529                             19506                           16070                             3436
4                            5180                              3677                            2827                              850

  healthcoverage_m26to34_privateall healthcoverage_m26to34_wprivate healthcoverage_m26to34_woprivate healthcoverage_m35to44_privateall  \
0                              4518                            3272                             1246                              4327
1                             19993                           15766                             4227                             24601
2                             30624                           22350                             8274                             30467
3                             22973                           18047                             4926                             24726
4                              5588                            3071                             2517                              5273

  healthcoverage_m35to44_wprivate healthcoverage_m35to44_woprivate healthcoverage_m45to54_privateall healthcoverage_m45to54_wprivate  \
0                            3150                             1177                              4433                            3639
1                           18496                             6105                             21646                           17391
2                           23706                             6761                             28985                           22945
3                           20364                             4362                             23083                           20434
4                            3496                             1777                              6282                            3932

  healthcoverage_m45to54_woprivate healthcoverage_m55to64_privateall healthcoverage_m55to64_wprivate healthcoverage_m55to64_woprivate  \
0                              794                              5222                            3746                             1476
1                             4255                             23209                           17928                             5281
2                             6040                             28816                           21945                             6871
3                             2649                             19011                           15911                             3100
4                             2350                              7150                            4515                             2635

  healthcoverage_m65to74_privateall healthcoverage_m65to74_wprivate healthcoverage_m65to74_woprivate healthcoverage_m75+_privateall  \
0                              4529                            2661                             1868                           2673
1                             18068                            9103                             8965                          10457

In [21]:
data = new_df

In [22]:
data = data.set_index(['NAME', 'GEO_ID']).transpose()
data.head()

NAME,"Anderson County, Tennessee","Hamilton County, Tennessee","Knox County, Tennessee","Rutherford County, Tennessee","Sevier County, Tennessee","Sumner County, Tennessee","Davidson County, Tennessee","Greene County, Tennessee","Madison County, Tennessee","Maury County, Tennessee","Montgomery County, Tennessee","Blount County, Tennessee","Bradley County, Tennessee","Putnam County, Tennessee","Robertson County, Tennessee","Shelby County, Tennessee","Sullivan County, Tennessee","Washington County, Tennessee","Williamson County, Tennessee","Wilson County, Tennessee",Tennessee,United States
GEO_ID,0500000US47001,0500000US47065,0500000US47093,0500000US47149,0500000US47155,0500000US47165,0500000US47037,0500000US47059,0500000US47113,0500000US47119,0500000US47125,0500000US47009,0500000US47011,0500000US47141,0500000US47147,0500000US47157,0500000US47163,0500000US47179,0500000US47187,0500000US47189,0400000US47,0100000US
agebysex_total_series,77576,369135,486677,352182,99517,200557,703953,70621,98775,104760,227900,137605,110162,81188,74098,924454,159265,134236,255735,151917,6975218,331893745
age_total_male,38441,178895,237254,174964,49578,98786,339586,35005,46248,50336,113798,66943,53995,39889,36915,439531,77808,66006,125693,76547,3413181,164350703
age_m_u5,1798,10836,13182,11215,2503,5389,22566,2018,2765,3152,9313,3313,2827,2326,2494,31974,3696,3194,6771,4156,202597,9552445
age_m_5to9,3105,11731,13092,13891,3280,5779,19813,2511,2646,3584,9494,3886,2972,2351,2007,33536,3280,3804,10232,6727,217844,10284656
age_m_10to14,2166,10297,16209,11180,3484,8568,18747,1510,3275,3115,8434,4188,4211,2185,3359,33534,5483,3798,10760,3969,226632,11155383

In [23]:
numcols = list(data.columns)
numcols
data[numcols] = data[numcols].astype(float)

In [24]:
GNRCCounties = [data[('Stewart County, Tennessee', '0500000US47161')],data[('Montgomery County, Tennessee', '0500000US47125')],
                data[('Houston County, Tennessee', '0500000US47083')],data[('Humphreys County, Tennessee', '0500000US47085')],
                data[('Dickson County, Tennessee', '0500000US47043')],data[('Cheatham County, Tennessee', '0500000US47021')],
                data[('Robertson County, Tennessee', '0500000US47147')],data[('Sumner County, Tennessee', '0500000US47165')],
                data[('Davidson County, Tennessee', '0500000US47037')],data[('Wilson County, Tennessee', '0500000US47189')],
                data[('Trousdale County, Tennessee', '0500000US47169')],data[('Williamson County, Tennessee', '0500000US47187')],
                data[('Rutherford County, Tennessee', '0500000US47149')]]
data['GNRC'] = sum(GNRCCounties)
GNRCCountiesAll = [data[('Stewart County, Tennessee', '0500000US47161')],data[('Montgomery County, Tennessee', '0500000US47125')],
                   data[('Houston County, Tennessee', '0500000US47083')],data[('Humphreys County, Tennessee', '0500000US47085')],
                   data[('Dickson County, Tennessee', '0500000US47043')],data[('Cheatham County, Tennessee', '0500000US47021')],
                   data[('Robertson County, Tennessee', '0500000US47147')],data[('Sumner County, Tennessee', '0500000US47165')],
                   data[('Davidson County, Tennessee', '0500000US47037')],data[('Wilson County, Tennessee', '0500000US47189')],
                   data[('Trousdale County, Tennessee', '0500000US47169')],data[('Williamson County, Tennessee', '0500000US47187')],
                   data[('Rutherford County, Tennessee', '0500000US47149')],data[('Maury County, Tennessee', '0500000US47119')]]
data['GNRC Region'] = sum(GNRCCountiesAll)
MPOCounties = [data[('Robertson County, Tennessee', '0500000US47147')],data[('Sumner County, Tennessee', '0500000US47165')],
               data[('Davidson County, Tennessee', '0500000US47037')],data[('Wilson County, Tennessee', '0500000US47189')],
               data[('Williamson County, Tennessee', '0500000US47187')],data[('Rutherford County, Tennessee', '0500000US47149')],
               data[('Maury County, Tennessee', '0500000US47119')]]
data['MPO'] = sum(MPOCounties)
RuthInc = [data[('Eagleville city, Tennessee', '1600000US4722360')],data[('La Vergne city, Tennessee', '1600000US4741200')],
           data[('Murfreesboro city, Tennessee', '1600000US4751560')],data[('Smyrna town, Tennessee', '1600000US4769420')]]
data[('Rutherford Incorporated', 'None')] = sum(RuthInc)
data[('Rutherford Unincorporated', 'None')] = data[('Rutherford County, Tennessee', '0500000US47149')] - data[('Rutherford Incorporated', 'None')]
WilsonInc = [data[('Lebanon city, Tennessee', '1600000US4741520')],data[('Mount Juliet city, Tennessee', '1600000US4750780')],
             data[('Watertown city, Tennessee', '1600000US4778320')]]
data[('Wilson Incorporated', 'None')] = sum(WilsonInc)
data[('Wilson Unincorporated', 'None')] = data[('Wilson County, Tennessee', '0500000US47189')] - data[('Wilson Incorporated', 'None')]
CheathInc = [data[('Ashland City town, Tennessee', '1600000US4702180')],data[('Kingston Springs town, Tennessee', '1600000US4739660')],
             data[('Pegram town, Tennessee', '1600000US4757480')],data[('Pleasant View city, Tennessee', '1600000US4759560')]]
data[('Cheatham Incorporated', 'None')] = sum(CheathInc)
data[('Cheatham Unincorporated', 'None')] = data[('Cheatham County, Tennessee', '0500000US47021')] - data[('Cheatham Incorporated', 'None')]
DicksInc = [data[('Burns town, Tennessee', '1600000US4709880')],data[('Charlotte town, Tennessee', '1600000US4713080')],
            data[('Dickson city, Tennessee', '1600000US4720620')],data[('Slayden town, Tennessee', '1600000US4769080')],
            data[('Vanleer town, Tennessee', '1600000US4776860')],data[('White Bluff town, Tennessee', '1600000US4779980')]]
data[('Dickson Incorporated', 'None')] = sum(DicksInc)
data[('Dickson Unincorporated', 'None')] = data[('Dickson County, Tennessee', '0500000US47043')] - data[('Dickson Incorporated', 'None')]
HumphInc = [data[('McEwen city, Tennessee', '1600000US4744840')],data[('New Johnsonville city, Tennessee', '1600000US4752820')],
            data[('Waverly city, Tennessee', '1600000US4778560')]]
data[('Humphreys Incorporated', 'None')] = sum(HumphInc)
data[('Humphreys Unincorporated', 'None')] = data[('Humphreys County, Tennessee', '0500000US47085')] - data[('Humphreys Incorporated', 'None')]
data[('Montgomery Incorporated', 'None')] = data[('Clarksville city, Tennessee', '1600000US4715160')]
data[('Montgomery Unincorporated', 'None')] = data[('Montgomery County, Tennessee', '0500000US47125')] - data[('Montgomery Incorporated', 'None')]

KeyError: ('Stewart County, Tennessee', '0500000US47161')

In [ ]:
data = data.transpose().reset_index()
data.head()

In [ ]:
data.info()

In [ ]:
data.to_feather('../../Raw Data/ACS20215YR')

In [ ]:
data.to_csv('../../Raw Data/ACS20215YR.csv')