###### Imports and Settings

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)
from warnings import simplefilter
simplefilter(action="ignore", category=pd.errors.PerformanceWarning)
import sqlite3 as sq

In [2]:
import sys
sys.path.append("../../../Functions and Dictionaries") # Adds higher directory to python modules path
import geodict
GNRC = geodict.GNRC
KY = geodict.KY
censusplaces = geodict.censusplaces

In [3]:
def percent(x, y):
    return (x/y)*100

## Calculations

## ALL:

In [4]:
data = pd.read_feather('../../Raw Data/SF12000')
coldropper = data.set_index(['NAME', 'GEO_ID'])

In [5]:
#population
data['Population'] = data['agebysex_total_series']
#age sex race
#small groups m and f
data['Male Under 5'] = data['age_m_u5']
data['Female Under 5'] = data['age_f_u5']
data['Male 5 to 14'] = data['age_m_5to9'] + data['age_m_10to14']
data['Female 5 to 14'] = data['age_f_5to9'] + data['age_f_10to14']
data['Male 15 to 24'] = data['age_m_15to17'] + data['age_m_18to19']+data['age_m_20']+data['age_m_21']+data['age_m_22to24']
data['Female 15 to 24'] = data['age_f_15to17'] + data['age_f_18to19']+data['age_f_20']+data['age_f_21']+data['age_f_22to24']
data['Male 5 to 9'] = data['age_m_5to9']
data['Female 5 to 9'] = data['age_f_5to9']
data['Male 10 to 14'] = data['age_m_10to14']
data['Female 10 to 14'] = data['age_f_10to14']
data['Male 15 to 17'] = data['age_m_15to17']
data['Female 15 to 17'] = data['age_f_15to17']
data['Male 18 to 24'] = data['age_m_18to19']+data['age_m_20']+data['age_m_21']+data['age_m_22to24']
data['Female 18 to 24'] = data['age_f_18to19']+data['age_f_20']+data['age_f_21']+data['age_f_22to24']
data['Male 25 to 34'] = data['age_m_25to29']+data['age_m_30to34']
data['Female 25 to 34'] = data['age_f_25to29']+data['age_f_30to34']
data['Male 35 to 44'] = data['age_m_35to39']+data['age_m_40to44']
data['Female 35 to 44'] = data['age_f_35to39']+data['age_f_40to44']
data['Male 45 to 54'] = data['age_m_45to49']+data['age_m_50to54']
data['Female 45 to 54'] = data['age_f_45to49']+data['age_f_50to54']
data['Male 55 to 64'] = data['age_m_55to59']+data['age_m_60to61']+data['age_m_62to64']
data['Female 55 to 64'] = data['age_f_55to59']+data['age_f_60to61']+data['age_f_62to64']
data['Male 65 to 74'] = data['age_m_65to66']+data['age_m_67to69']+data['age_m_70to74']
data['Female 65 to 74'] = data['age_f_65to66']+data['age_f_67to69']+data['age_f_70to74']
data['Male 75 to 84'] = data['age_m_75to79']+data['age_m_80to84']
data['Female 75 to 84'] = data['age_f_75to79']+data['age_f_80to84']
data['Male 85 and Older'] = data['age_m_85+']
data['Female 85 and Older'] = data['age_f_85+']
#age group breakouts
data['Age:Under 5'] = data['Male Under 5']+data['Female Under 5']
data['Age %:Under 5'] = percent(data['Age:Under 5'], data['Population'])
data['Age:5 to 9'] = data['Male 5 to 9']+data['Female 5 to 9']
data['Age%:5 to 9'] = percent(data['Age:5 to 9'], data['Population'])
data['Age:10 to 14'] = data['Male 10 to 14']+data['Female 10 to 14']
data['Age%:10 to 14'] = percent(data['Age:10 to 14'], data['Population'])
data['Age:15 to 17'] = data['Male 15 to 17']+data['Female 15 to 17']
data['Age%:15 to 17'] = percent(data['Age:15 to 17'], data['Population'])
data['Age:18 to 24'] = data['Male 18 to 24']+data['Female 18 to 24']
data['Age%:18 to 24'] = percent(data['Age:18 to 24'], data['Population'])
data['Age:25 to 34'] = data['Male 25 to 34']+data['Female 25 to 34']
data['Age%:25 to 34'] = percent(data['Age:25 to 34'], data['Population'])
data['Age:35 to 44'] = data['Male 35 to 44']+data['Female 35 to 44']
data['Age%:35 to 44'] = percent(data['Age:35 to 44'], data['Population'])
data['Age:45 to 54'] = data['Male 35 to 44']+data['Female 45 to 54']
data['Age%:45 to 54'] = percent(data['Age:45 to 54'], data['Population'])
data['Age:55 to 64'] = data['Male 55 to 64']+data['Female 55 to 64']
data['Age%:55 to 64'] = percent(data['Age:55 to 64'], data['Population'])
data['Age:65 to 74'] = data['Male 65 to 74']+data['Female 65 to 74']
data['Age%:65 to 74'] = percent(data['Age:65 to 74'], data['Population'])
data['Age:75 to 84'] = data['Male 75 to 84']+data['Female 75 to 84']
data['Age%:75 to 84'] = percent(data['Age:75 to 84'], data['Population'])
data['Age:85 and Older'] = data['Male 85 and Older']+data['Female 85 and Older']
data['Age%:85 and Older'] = percent(data['Age:85 and Older'], data['Population'])
data['Age:School Age 5 to 18'] = data['Age:5 to 9']+data['Age:10 to 14']+data['Age:15 to 17']
data['Age%:School Age 5 to 18'] = percent(data['Age:School Age 5 to 18'], data['Population'])
#age brackets
u18list = [data['Male Under 5'],data['Female Under 5'],data['Male 5 to 9'],data['Female 5 to 9'],data['Male 10 to 14'],data['Female 10 to 14'],data['Male 15 to 17'],
           data['Female 15 to 17']]
data['Age:Under 18'] = sum(u18list)
data['Age%:Under 18'] = percent(data['Age:Under 18'], data['Population'])
eighteento54list = [data['Male 18 to 24'],data['Female 18 to 24'],data['Male 25 to 34'],data['Female 25 to 34'],data['Male 35 to 44'],data['Female 35 to 44'],
              data['Male 45 to 54'],data['Female 45 to 54']]
data['Age:18 to 54'] = sum(eighteento54list)
data['Age%:18 to 54'] = percent(data['Age:18 to 54'], data['Population'])
#18to64
eighteento64list = [data['Male 18 to 24'],data['Female 18 to 24'],data['Male 25 to 34'],data['Female 25 to 34'],data['Male 35 to 44'],data['Female 35 to 44'],
                    data['Male 45 to 54'],data['Female 45 to 54'], data['Male 55 to 64'],data['Female 55 to 64']]
data['Age:18 to 64'] = sum(eighteento64list)
data['Age%:18 to 64'] = percent(data['Age:18 to 64'], data['Population'])
fifty5pluslist = [data['Male 55 to 64'],data['Female 55 to 64'],data['Male 65 to 74'],data['Female 65 to 74'],data['Male 75 to 84'],data['Female 75 to 84'],
                  data['Male 85 and Older'],data['Female 85 and Older']]
data['Age:55 and Older'] = sum(fifty5pluslist)
data['Age%:55 and Older'] = percent(data['Age:55 and Older'], data['Population'])
#65+
sixty5pluslist = [data['Male 65 to 74'],data['Female 65 to 74'],data['Male 75 to 84'],data['Female 75 to 84'],data['Male 85 and Older'],data['Female 85 and Older']]
data['Age:65 and Older'] = sum(sixty5pluslist)
data['Age%:65 and Older'] = percent(data['Age:65 and Older'], data['Population'])
#race and ethnicity
#White Alone
data['White Alone'] = data['raceeth_white_alone']
data['White Alone %'] = percent(data['White Alone'], data['Population'])
#Population not White
data['Non-White Population: Race'] = data['Population'] - data['White Alone']
#Black or African American Alone 
data['Black or African American Alone'] = data['raceeth_blackafricanamerican_alone']
data['Black or African American Alone %'] = percent(data['Black or African American Alone'], data['Population'])
data['Black or African American Alone % Non-White Population'] = percent(data['Black or African American Alone'], data['Non-White Population: Race'])
#American Indian and Alaska Native Alone
data['American Indian Alaska Native Alone'] = data['raceeth_americanindianalaskanative_alone']
data['American Indian Alaska Native Alone %'] = percent(data['American Indian Alaska Native Alone'], data['Population'])
data['American Indian Alaska Native Alone % Non-White Population'] = percent(data['American Indian Alaska Native Alone'], data['Non-White Population: Race'])
#Asian Alone
data['Asian Alone'] = data['raceeth_asian_alone']
data['Asian Alone %'] = percent(data['Asian Alone'], data['Population'])
data['Asian Alone % Non-White Population'] = percent(data['Asian Alone'], data['Non-White Population: Race'])
#Native Hawaiian Other Pacific Islander Alone
data['Native Hawaiian Other Pacific Islander Alone'] = data['raceeth_nativehawaiianotherpacificislander_alone']
data['Native Hawaiian Other Pacific Islander Alone %'] = percent(data['Native Hawaiian Other Pacific Islander Alone'], data['Population'])
data['Native Hawaiian Other Pacific Islander Alone % Non-White Population'] = percent(data['Native Hawaiian Other Pacific Islander Alone'], data['Non-White Population: Race'])
#Some Other Race Alone
data['Some Other Race Alone'] = data['raceeth_someotherrace_alone']
data['Some Other Race Alone %'] = percent(data['Some Other Race Alone'],data['Population'])
data['Some Other Race Alone % Non-White Population'] = percent(data['Some Other Race Alone'], data['Non-White Population: Race'])
#Two or More Races
data['Two or More Races'] = data['raceeth_twoormoreraces_alone']
data['Two or More Races %'] = percent(data['Two or More Races'], data['Population'])
data['Two or More Races % Non-White Population'] = percent(data['Two or More Races'], data['Non-White Population: Race'])
#Hispanic or Latino
data['Hispanic or Latino'] = data['raceeth_hispanicorlatino']
data['Hispanic or Latino %'] = percent(data['Hispanic or Latino'], data['Population'])
#not hispanic or latino
data['Not Hispanic or Latino'] = data['Population'] - data['Hispanic or Latino']
data['Not Hispanic or Latino %'] = percent(data['Not Hispanic or Latino'], data['Population'])
#Data Minority
data['Minority'] = data['Population'] - data['raceeth_whitealone_nothispanicorlatino']
data['Minority %'] = percent(data['Minority'], data['Population'])
#not minority
data['White Alone Not Hispanic or Latino'] = data['raceeth_whitealone_nothispanicorlatino']
data['White Alone Not Hispanic or Latino %'] = percent(data['White Alone Not Hispanic or Latino'], data['Population'])
#households
data['Total Households'] = data['hhtype_total_series']
data['Family Households'] = data['hhtype_twoormore_family']
data['Family Households: Married Couple Family'] = data['hhtype_twoormore_family_marriedcouplefam']
data['Household Type%: Family, Married Couple Households'] = percent(data['Family Households: Married Couple Family'], data['hhtype_total_series'])
data['Family Households: Not Married Couple Family'] = data['hhtype_twoormore_family_otherfam']
data['Household Type%: Family, Not Married Couple Households'] = percent(data['Family Households: Not Married Couple Family'], data['hhtype_total_series'])
data['Family Households: Not Married Couple: Male no Spouse'] = data['hhtype_twoormore_family_otherfam_malenospouse']
data['Family Households: Not Married Couple: Female no Spouse'] = data['hhtype_twoormore_family_otherfam_femalenospouse']
data['Nonfamily Households'] = data['hhtype_twoormore_nonfamily'] + data['hhtype_oneperson']
data['Nonfamily Households: Householder Alone'] = data['hhtype_oneperson']
data['Household Type%: Nonfamily, Householder Alone'] = percent(data['Nonfamily Households: Householder Alone'], data['hhtype_total_series'])
data['Nonfamily Households: Householder not Alone'] = data['hhtype_twoormore_nonfamily']
data['Household Type%: Nonfamily, Householder Not Alone'] = percent(data['Nonfamily Households: Householder not Alone'], data['hhtype_total_series'])
#average household size
data['Average Household Size'] = data['hhsize_avg']
#occupancy
data['Occupancy:Total Households'] = data['occupancy_total_series']
data['Occupancy:Occupied Units'] = data['occupancy_occupiedunits']
data['Occupancy%:Occupied Units'] = percent(data['Occupancy:Occupied Units'], data['Occupancy:Total Households'])
data['Occupancy:Vacant Units'] = data['occupancy_vacantunits']
data['Occupancy%:Vacant Units'] = percent(data['Occupancy:Vacant Units'], data['Occupancy:Total Households'])
#tenure
data['Tenure:Total Households'] = data['tenure_total_series']
data['Tenure:Owners'] = data['tenure_owneroccunits']
data['Tenure%:Owners'] = percent(data['Tenure:Owners'], data['Tenure:Total Households'])
data['Tenure:Renters'] = data['tenure_renteroccunits']
data['Tenure%:Renters'] = percent(data['Tenure:Renters'], data['Tenure:Total Households'])

In [6]:
cols = coldropper.columns
data = data.drop(columns = cols)

In [7]:
data.head()

,NAME,GEO_ID,Population,Male Under 5,Female Under 5,Male 5 to 14,Female 5 to 14,Male 15 to 24,Female 15 to 24,Male 5 to 9,Female 5 to 9,Male 10 to 14,Female 10 to 14,Male 15 to 17,Female 15 to 17,Male 18 to 24,Female 18 to 24,Male 25 to 34,Female 25 to 34,Male 35 to 44,Female 35 to 44,Male 45 to 54,Female 45 to 54,Male 55 to 64,Female 55 to 64,Male 65 to 74,Female 65 to 74,Male 75 to 84,Female 75 to 84,Male 85 and Older,Female 85 and Older,Age:Under 5,Age %:Under 5,Age:5 to 9,Age%:5 to 9,Age:10 to 14,Age%:10 to 14,Age:15 to 17,Age%:15 to 17,Age:18 to 24,Age%:18 to 24,Age:25 to 34,Age%:25 to 34,Age:35 to 44,Age%:35 to 44,Age:45 to 54,Age%:45 to 54,Age:55 to 64,Age%:55 to 64,Age:65 to 74,Age%:65 to 74,Age:75 to 84,Age%:75 to 84,Age:85 and Older,Age%:85 and Older,Age:School Age 5 to 18,Age%:School Age 5 to 18,Age:Under 18,Age%:Under 18,Age:18 to 54,Age%:18 to 54,Age:18 to 64,Age%:18 to 64,Age:55 and Older,Age%:55 and Older,Age:65 and Older,Age%:65 and Older,White Alone,White Alone %,Non-White Population: Race,Black or African American Alone,Black or African American Alone %,Black or African American Alone % Non-White Population,American Indian Alaska Native Alone,American Indian Alaska Native Alone %,American Indian Alaska Native Alone % Non-White Population,Asian Alone,Asian Alone %,Asian Alone % Non-White Population,Native Hawaiian Other Pacific Islander Alone,Native Hawaiian Other Pacific Islander Alone %,Native Hawaiian Other Pacific Islander Alone % Non-White Population,Some Other Race Alone,Some Other Race Alone %,Some Other Race Alone % Non-White Population,Two or More Races,Two or More Races %,Two or More Races % Non-White Population,Hispanic or Latino,Hispanic or Latino %,Not Hispanic or Latino,Not Hispanic or Latino %,Minority,Minority %,White Alone Not Hispanic or Latino,White Alone Not Hispanic or Latino %,Total Households,Family Households,Family Households: Married Couple Family,"Household Type%: Family, Married Couple Households",Family Households: Not Married Couple Family,"Household Type%: Family, Not Married Couple Households",Family Households: Not Married Couple: Male no Spouse,Family Households: Not Married Couple: Female no Spouse,Nonfamily Households,Nonfamily Households: Householder Alone,"Household Type%: Nonfamily, Householder Alone",Nonfamily Households: Householder not Alone,"Household Type%: Nonfamily, Householder Not Alone",Average Household Size,Occupancy:Total Households,Occupancy:Occupied Units,Occupancy%:Occupied Units,Occupancy:Vacant Units,Occupancy%:Vacant Units,Tenure:Total Households,Tenure:Owners,Tenure%:Owners,Tenure:Renters,Tenure%:Renters
0,"Anderson County, Tennessee",0500000US47001,71330.0,2026.0,1950.0,4936.0,4667.0,4163.0,4119.0,2462.0,2284.0,2474.0,2383.0,1489.0,1467.0,2674.0,2652.0,4160.0,4447.0,5265.0,5602.0,5111.0,5519.0,3658.0,3883.0,2595.0,3410.0,1724.0,2729.0,371.0,995.0,3976.0,5.574092,4746.0,6.653582,4857.0,6.809197,2956.0,4.144119,5326.0,7.466704,8607.0,12.066452,10867.0,15.234824,10784.0,15.118463,7541.0,10.571989,6005.0,8.418618,4453.0,6.242815,1366.0,1.915043,12559.0,17.606898,16535.0,23.180990,35430.0,49.670545,42971.0,60.242535,19365.0,27.148465,11824.0,16.576476,66593.0,93.359035,4737.0,2766.0,3.877751,58.391387,226.0,0.316837,4.770952,593.0,0.831347,12.518472,9.0,0.012617,0.189994,274.0,0.384130,5.784252,869.0,1.218281,18.344944,787.0,1.103323,70543.0,98.896677,5206.0,7.298472,66124.0,92.701528,29780.0,20513.0,16024.0,53.807925,4489.0,15.073875,1063.0,3426.0,9267.0,8259.0,27.733378,1008.0,3.384822,2.37,32451.0,29780.0,91.769129,2671.0,8.230871,29780.0,21592.0,72.505037,8188.0,27.494963
1,"Bedford County, Tennessee",0500000US47003,37586.0,1370.0,1397.0,2745.0,2608.0,2803.0,2491.0,1384.0,1335.0,1361.0,1273.0,791.0,776.0,2012.0,1715.0,2803.0,2657.0,2880.0,2815.0,2408.0,2365.0,1658.0,1830.0,1194.0,1363.0,639.0,995.0,145.0,420.0,2767.0,7.361784,2719.0,7.234077,2634.0,7.007928,1567.0,4.169106,3727.0,9.915926,5460.0,14.526685,5695.0,15.151918,5245.0,13.954664,3488.0,9.280051,2557.0,6.803065,1634.0,4.347363,565.0,1.503219,6920.0,18.411111,9687.0,25.772894,19655.0,52.293407,23143.0,61.573458,8244.0,21.933699,4756.0,12.653648,32640.0,86.840845,4946.0,3189.0,8.484542,64.476345,105.0,0.279359,2.122928,170.0,0.452296,3.437121,20.0,0.053211,0.404367,1025.0,2.727079,20.723817,437.0,1.162667,8.835423,2811.0,7.478849,34775.0,92.521151,6526.0,17.362848,31060.0,82.637152,13905.0,10350.0,7968.0,57.303128,2382.0,17.130529,724.0,1658.0,3555.0,2987.0,21.481481,568.0,4.084862,2.67,14990.0,13905.0,92.761841,1085.0,7.238159,13905.0,10226.0,73.541891,3679.0,26.458109
2,"Benton County, Tennessee",0500000US47005,16537.0,434.0,421.0,1085.0,1054.0,898.0,909.0,539.0,543.0,546.0,511.0,328.0,319.0,570.0,590.0,972.0,948.0,1170.0,1244.0,1177.0,1198.0,1055.0,1040.0,735.0,868.0,376.0,600.0,104.0,249.0,855.0,5.170224,1082.0,6.542904,1057.0,6.391728,647.0,3.912439,1160.0,7.014573,1920.0,11.610328,2414.0,14.597569,2368.0,14.319405,2095.0,12.668561,1603.0,9.693415,976.0,5.901917,353.0,2.134607,2786.0,16.847070,3641.0,22.017295,7869.0,47.584205,9964.0,60.252767,5027.0,30.398500,2932.0,17.729939,15948.0,96.438290,589.0,348.0,2.104372,59.083192,54.0,0.326540,9.168081,40.0,0.241882,6.791171,0.0,0.000000,0.000000,33.0,0.199553,5.602716,114.0,0.689363,19.354839,157.0,0.949386,16380.0,99.050614,703.0,4.251073,15834.0,95.748927,6863.0,4888.0,3987.0,58.094128,901.0,13.128370,250.0,651.0,1975.0,1766.0,25.732187,209.0,3.045315,2.37,8595.0,6863.0,79.848749,1732.0,20.151251,6863.0,5527.0,80.533294,1336.0,19.466706
3,"Bledsoe County, Tennessee",0500000US47007,12367.0,384.0,345.0,856.0,745.0,921.0,639.0,431.0,363.0,425.0,382.0,316.0,208.0,605.0,431.0,1047.0,723.0,1232.0,874.0,1008.0,849.0,713.0,616.0,396.0,451.0,174.0,282.0,40.0,72.0,729.0,5.894720,794.0,6.420312,807.0,6.525431,524.0,4.237083,1036.0,8.377133,1770.0,14.312283,2106.0,17.029191,2081.0,16.827040,1329.0,10.746341,847.0,6.848872,456.0,3.687232,112.0,0.905636,2125.0,17.182825,2854.0,23.077545,6769.0,54.734374,8098.0,65.480715,2744.0,22.188081,1415.0,11.441740,11680.0,94.444894,687.0,458.0,3.703404,66.666667,47.0,0.380044,6.841339,14.0,0.113204,2.037846,3.0,0.024258,0.436681,23.0,0.185979,3.347889,142.0,1.148217,20.669578,138.0,1.115873,12229.0,98.884127,784.0,6.339452,11583.0,93.660548,4430.0,3312.0,2726.0,61.534989,586.0,13.227991,182.0,404.0,1118.0,981.0,22.144470,137.0,3.092551,2.53,5142.0,4430.0,86.153248,712.0,13.846752,4430.0,3622.0,81.760722,808.0,18.239278
4,"Blount County, Tennessee",0500000US47009,105823.0,3073.0,3032.0,7144.0,6772.0,6606.0,6328.0,3497.0,3369.0,3647.0,3403.0,2124.0,1985.0,4482.0,4343.0,7002.0,7217.0,8255.0,8618.0,7651.0,7958.0,5437.0,5816.0,3514.0,4318.0,2068.0,3319.0,477.0,1218.0,6105.0,5.769067,6866.0,6.488193,7050.0,6.662068,4109.0,3.882899,8825.0,8.339397,14219.0,13.436588,16873.0,15.944549,16213.0,15.320866,11253.0,10.633794,7832.0,7.401038,5387.0,5.090576,1695.0,1.601731,18025.0,17.033159,24130.0,22.802226,55526.0,52.470635,66779.0,63.104429,26167.0,24.727139,14914.0,14.093345,100241.0,94.725154,5582.0,3077.0,2.907685,55.123612,308.0,0.291052,5.517736,759.0,0.717235,13.597277,27.0,0.025514,0.483698,363.0,0.343026,6.503046,1048.0,0.990333,18.774633,1120.0,1.058371,104703.0,98.941629,6227.0,5.884354,99596.0,94.115646,42667.0,30642.0,24936.0,58.443293,5706.0,13.373333,1442.0,4264.0,12025.0,10391.0,24.353716,1634.0,3.829658,2.43,47059.0,42667.0,90.667035,4392.0,9.332965,42667.0,32381.0,75.892376,10286.0,24.107624

In [8]:
data = data.set_index('NAME').transpose()
#make sure there is no erroneus median or average data for aggregated regions
region_cols = ['GNRC', 'GNRC Region', 'MPO', 'Rutherford Incorporated', 'Rutherford Unincorporated', 'Wilson Incorporated', 'Wilson Unincorporated', 
               'Cheatham Incorporated', 'Cheatham Unincorporated', 'Dickson Incorporated', 'Dickson Unincorporated', 'Humphreys Incorporated', 
               'Humphreys Unincorporated', 'Montgomery Incorporated', 'Montgomery Unincorporated']
data.loc[data.index.str.contains('Median', case = False), region_cols] = 0
data.loc[data.index.str.contains('Average', case = False), region_cols] = 0

In [9]:
data = data.transpose().reset_index(drop = False)

In [10]:
cols = list(data.columns)
cols.remove('NAME')
cols.remove('GEO_ID')
data[cols] = data[cols].astype(float)

In [11]:
data['Source'] = '2000 Decennial SF1'

In [12]:
#final check
data.head(3)

,NAME,GEO_ID,Population,Male Under 5,Female Under 5,Male 5 to 14,Female 5 to 14,Male 15 to 24,Female 15 to 24,Male 5 to 9,Female 5 to 9,Male 10 to 14,Female 10 to 14,Male 15 to 17,Female 15 to 17,Male 18 to 24,Female 18 to 24,Male 25 to 34,Female 25 to 34,Male 35 to 44,Female 35 to 44,Male 45 to 54,Female 45 to 54,Male 55 to 64,Female 55 to 64,Male 65 to 74,Female 65 to 74,Male 75 to 84,Female 75 to 84,Male 85 and Older,Female 85 and Older,Age:Under 5,Age %:Under 5,Age:5 to 9,Age%:5 to 9,Age:10 to 14,Age%:10 to 14,Age:15 to 17,Age%:15 to 17,Age:18 to 24,Age%:18 to 24,Age:25 to 34,Age%:25 to 34,Age:35 to 44,Age%:35 to 44,Age:45 to 54,Age%:45 to 54,Age:55 to 64,Age%:55 to 64,Age:65 to 74,Age%:65 to 74,Age:75 to 84,Age%:75 to 84,Age:85 and Older,Age%:85 and Older,Age:School Age 5 to 18,Age%:School Age 5 to 18,Age:Under 18,Age%:Under 18,Age:18 to 54,Age%:18 to 54,Age:18 to 64,Age%:18 to 64,Age:55 and Older,Age%:55 and Older,Age:65 and Older,Age%:65 and Older,White Alone,White Alone %,Non-White Population: Race,Black or African American Alone,Black or African American Alone %,Black or African American Alone % Non-White Population,American Indian Alaska Native Alone,American Indian Alaska Native Alone %,American Indian Alaska Native Alone % Non-White Population,Asian Alone,Asian Alone %,Asian Alone % Non-White Population,Native Hawaiian Other Pacific Islander Alone,Native Hawaiian Other Pacific Islander Alone %,Native Hawaiian Other Pacific Islander Alone % Non-White Population,Some Other Race Alone,Some Other Race Alone %,Some Other Race Alone % Non-White Population,Two or More Races,Two or More Races %,Two or More Races % Non-White Population,Hispanic or Latino,Hispanic or Latino %,Not Hispanic or Latino,Not Hispanic or Latino %,Minority,Minority %,White Alone Not Hispanic or Latino,White Alone Not Hispanic or Latino %,Total Households,Family Households,Family Households: Married Couple Family,"Household Type%: Family, Married Couple Households",Family Households: Not Married Couple Family,"Household Type%: Family, Not Married Couple Households",Family Households: Not Married Couple: Male no Spouse,Family Households: Not Married Couple: Female no Spouse,Nonfamily Households,Nonfamily Households: Householder Alone,"Household Type%: Nonfamily, Householder Alone",Nonfamily Households: Householder not Alone,"Household Type%: Nonfamily, Householder Not Alone",Average Household Size,Occupancy:Total Households,Occupancy:Occupied Units,Occupancy%:Occupied Units,Occupancy:Vacant Units,Occupancy%:Vacant Units,Tenure:Total Households,Tenure:Owners,Tenure%:Owners,Tenure:Renters,Tenure%:Renters,Source
0,"Anderson County, Tennessee",0500000US47001,71330.0,2026.0,1950.0,4936.0,4667.0,4163.0,4119.0,2462.0,2284.0,2474.0,2383.0,1489.0,1467.0,2674.0,2652.0,4160.0,4447.0,5265.0,5602.0,5111.0,5519.0,3658.0,3883.0,2595.0,3410.0,1724.0,2729.0,371.0,995.0,3976.0,5.574092,4746.0,6.653582,4857.0,6.809197,2956.0,4.144119,5326.0,7.466704,8607.0,12.066452,10867.0,15.234824,10784.0,15.118463,7541.0,10.571989,6005.0,8.418618,4453.0,6.242815,1366.0,1.915043,12559.0,17.606898,16535.0,23.180990,35430.0,49.670545,42971.0,60.242535,19365.0,27.148465,11824.0,16.576476,66593.0,93.359035,4737.0,2766.0,3.877751,58.391387,226.0,0.316837,4.770952,593.0,0.831347,12.518472,9.0,0.012617,0.189994,274.0,0.384130,5.784252,869.0,1.218281,18.344944,787.0,1.103323,70543.0,98.896677,5206.0,7.298472,66124.0,92.701528,29780.0,20513.0,16024.0,53.807925,4489.0,15.073875,1063.0,3426.0,9267.0,8259.0,27.733378,1008.0,3.384822,2.37,32451.0,29780.0,91.769129,2671.0,8.230871,29780.0,21592.0,72.505037,8188.0,27.494963,2000 Decennial SF1
1,"Bedford County, Tennessee",0500000US47003,37586.0,1370.0,1397.0,2745.0,2608.0,2803.0,2491.0,1384.0,1335.0,1361.0,1273.0,791.0,776.0,2012.0,1715.0,2803.0,2657.0,2880.0,2815.0,2408.0,2365.0,1658.0,1830.0,1194.0,1363.0,639.0,995.0,145.0,420.0,2767.0,7.361784,2719.0,7.234077,2634.0,7.007928,1567.0,4.169106,3727.0,9.915926,5460.0,14.526685,5695.0,15.151918,5245.0,13.954664,3488.0,9.280051,2557.0,6.803065,1634.0,4.347363,565.0,1.503219,6920.0,18.411111,9687.0,25.772894,19655.0,52.293407,23143.0,61.573458,8244.0,21.933699,4756.0,12.653648,32640.0,86.840845,4946.0,3189.0,8.484542,64.476345,105.0,0.279359,2.122928,170.0,0.452296,3.437121,20.0,0.053211,0.404367,1025.0,2.727079,20.723817,437.0,1.162667,8.835423,2811.0,7.478849,34775.0,92.521151,6526.0,17.362848,31060.0,82.637152,13905.0,10350.0,7968.0,57.303128,2382.0,17.130529,724.0,1658.0,3555.0,2987.0,21.481481,568.0,4.084862,2.67,14990.0,13905.0,92.761841,1085.0,7.238159,13905.0,10226.0,73.541891,3679.0,26.458109,2000 Decennial SF1
2,"Benton County, Tennessee",0500000US47005,16537.0,434.0,421.0,1085.0,1054.0,898.0,909.0,539.0,543.0,546.0,511.0,328.0,319.0,570.0,590.0,972.0,948.0,1170.0,1244.0,1177.0,1198.0,1055.0,1040.0,735.0,868.0,376.0,600.0,104.0,249.0,855.0,5.170224,1082.0,6.542904,1057.0,6.391728,647.0,3.912439,1160.0,7.014573,1920.0,11.610328,2414.0,14.597569,2368.0,14.319405,2095.0,12.668561,1603.0,9.693415,976.0,5.901917,353.0,2.134607,2786.0,16.847070,3641.0,22.017295,7869.0,47.584205,9964.0,60.252767,5027.0,30.398500,2932.0,17.729939,15948.0,96.438290,589.0,348.0,2.104372,59.083192,54.0,0.326540,9.168081,40.0,0.241882,6.791171,0.0,0.000000,0.000000,33.0,0.199553,5.602716,114.0,0.689363,19.354839,157.0,0.949386,16380.0,99.050614,703.0,4.251073,15834.0,95.748927,6863.0,4888.0,3987.0,58.094128,901.0,13.128370,250.0,651.0,1975.0,1766.0,25.732187,209.0,3.045315,2.37,8595.0,6863.0,79.848749,1732.0,20.151251,6863.0,5527.0,80.533294,1336.0,19.466706,2000 Decennial SF1

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Columns: 121 entries, NAME to Source
dtypes: float64(118), object(3)
memory usage: 187.3+ KB

In [14]:
conn = sq.connect('../../Outputs/CensusBureau.db')
data.to_sql('CensusBureau_SF1_2000', conn, if_exists = 'replace', index = False)

198