###### Imports and Settings

In [14]:
import pandas as pd
pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)
from warnings import simplefilter
simplefilter(action="ignore", category=pd.errors.PerformanceWarning)
import sqlite3 as sq
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)

In [15]:
import sys
sys.path.append("../../../Functions and Dictionaries") # Adds higher directory to python modules path
import geodict
GNRC = geodict.GNRC
KY = geodict.KY
censusplaces = geodict.censusplaces

In [16]:
def percent(x, y):
    return (x/y)*100

## Calculations

# ALL:

In [17]:
data = pd.read_feather('../../Raw Data/ACS2016CEDS')
coldropper = data.set_index(['NAME', 'GEO_ID'])

In [18]:
#educational attainment
data['Ed:Population 25+ Educational Attainment'] = data['attainment_total_over25_series']
lesshighschoollist = [data['attainment_noschooling'],data['attainment_nurseryschool'],data['attainment_kindergarten'],data['attainment_1stgrade'],
                      data['attainment_2ndgrade'],data['attainment_3rdgrade'],data['attainment_4thgrade'],data['attainment_5thgrade'],data['attainment_6thgrade'],
                      data['attainment_7thgrade'],data['attainment_8thgrade'],data['attainment_9thgrade'],data['attainment_10thgrade'],data['attainment_11thgrade'],
                      data['attainment_12thgradenodiploma']]
data['Ed:Less than High School'] = sum(lesshighschoollist)
data['Ed%:Less than High School'] = percent(data['Ed:Less than High School'], data['Ed:Population 25+ Educational Attainment'])
data['Ed:High School Graduate or Equivalency'] = data['attainment_regularhighschooldiploma']+data['attainment_gedoralternativecredential']
data['Ed%:High School Graduate or Equivalency'] = percent(data['Ed:High School Graduate or Equivalency'], data['Ed:Population 25+ Educational Attainment'])
highormore = [data['attainment_regularhighschooldiploma'],data['attainment_gedoralternativecredential'],data['attainment_somecollegelessthan1year'],
              data['attainment_somecollege1ormoreyearsnodegree'],data['attainment_associatesdegree'],data['attainment_bachelorsdegree'],
              data['attainment_mastersdegree'],data['attainment_professionalschooldegree'],data['attainment_doctoratedegree']]
data['Ed:High School Graduate or More'] = sum(highormore)
data['Ed%:High School Graduate or More'] = percent(sum(highormore),data['Ed:Population 25+ Educational Attainment'])
data['Ed:Some College'] = data['attainment_somecollegelessthan1year']+data['attainment_somecollege1ormoreyearsnodegree']
data['Ed%:Some College'] = percent(data['Ed:Some College'], data['Ed:Population 25+ Educational Attainment'])
somecollegeormore = [data['attainment_somecollege1ormoreyearsnodegree'],data['attainment_associatesdegree'],data['attainment_bachelorsdegree'],
                     data['attainment_mastersdegree'],data['attainment_professionalschooldegree'],data['attainment_doctoratedegree']]
data['Ed%:Some College or More'] = percent(sum(somecollegeormore),data['Ed:Population 25+ Educational Attainment'])
data['Ed:Associates'] = data['attainment_associatesdegree']
data['Ed%:Associates'] = percent(data['Ed:Associates'], data['Ed:Population 25+ Educational Attainment'])
data['Ed:Bachelors'] = data['attainment_bachelorsdegree']
data['Ed%:Bachelors'] = percent(data['Ed:Bachelors'], data['Ed:Population 25+ Educational Attainment'])
bachormore = [data['attainment_bachelorsdegree'],data['attainment_mastersdegree'],data['attainment_professionalschooldegree'],data['attainment_doctoratedegree']]
data['Ed:Bachelors or More'] = sum(bachormore)
data['Ed%:Bachelors or More'] = percent(sum(bachormore),data['Ed:Population 25+ Educational Attainment'])
data['Ed:Masters'] = data['attainment_mastersdegree']
mastersormore = [data['attainment_mastersdegree'],data['attainment_professionalschooldegree'],data['attainment_doctoratedegree']]
data['Ed:Masters or More'] = sum(mastersormore)
data['Ed%:Masters or More'] = percent(sum(mastersormore),data['Ed:Population 25+ Educational Attainment'])
data['Ed%:Masters'] = percent(data['Ed:Masters'], data['Ed:Population 25+ Educational Attainment'])
data['Ed:Professional School Degree'] = data['attainment_professionalschooldegree']
data['Ed%:Professional School Degree'] = percent(data['Ed:Professional School Degree'], data['Ed:Population 25+ Educational Attainment'])
proformore = [data['attainment_mastersdegree'],data['attainment_professionalschooldegree'],data['attainment_doctoratedegree']]
data['Ed%:Professional School Degree or More'] = percent(sum(proformore),data['Ed:Population 25+ Educational Attainment'])
data['Ed:Doctorate Degree'] = data['attainment_doctoratedegree']
data['Ed%:Doctorate Degree'] = percent(data['Ed:Doctorate Degree'], data['Ed:Population 25+ Educational Attainment'])
#employment status
armedforces = [data['lfstatus_m_16to19_inlf_armedforces'],data['lfstatus_m_20to21_inlf_armedforces'],data['lfstatus_m_22to24_inlf_armedforces'],
               data['lfstatus_m_25to29_inlf_armedforces'],data['lfstatus_m_30to34_inlf_armedforces'],data['lfstatus_m_35to44_inlf_armedforces'],
               data['lfstatus_m_45to54_inlf_armedforces'],data['lfstatus_m_55to59_inlf_armedforces'],data['lfstatus_m_60to61_inlf_armedforces'],
               data['lfstatus_m_62to64_inlf_armedforces'],
               data['lfstatus_f_16to19_inlf_armedforces'],data['lfstatus_f_20to21_inlf_armedforces'],
               data['lfstatus_f_22to24_inlf_armedforces'],data['lfstatus_f_25to29_inlf_armedforces'],data['lfstatus_f_30to34_inlf_armedforces'],
               data['lfstatus_f_35to44_inlf_armedforces'],data['lfstatus_f_45to54_inlf_armedforces'],data['lfstatus_f_55to59_inlf_armedforces'],
               data['lfstatus_f_60to61_inlf_armedforces'],data['lfstatus_f_62to64_inlf_armedforces']]
data['Employment:Armed Forces'] = sum(armedforces)
notinlf = [data['lfstatus_m_16to19_notinlf'],data['lfstatus_m_20to21_notinlf'],data['lfstatus_m_22to24_notinlf'],
               data['lfstatus_m_25to29_notinlf'],data['lfstatus_m_30to34_notinlf'],data['lfstatus_m_35to44_notinlf'],
               data['lfstatus_m_45to54_notinlf'],data['lfstatus_m_55to59_notinlf'],data['lfstatus_m_60to61_notinlf'],
               data['lfstatus_m_62to64_notinlf'],data['lfstatus_m_65to69_notinlf'],data['lfstatus_m_70to74_notinlf'],
               data['lfstatus_m_75andolder_notinlf'],
               data['lfstatus_f_16to19_notinlf'],data['lfstatus_f_20to21_notinlf'],
               data['lfstatus_f_22to24_notinlf'],data['lfstatus_f_25to29_notinlf'],data['lfstatus_f_30to34_notinlf'],
               data['lfstatus_f_35to44_notinlf'],data['lfstatus_f_45to54_notinlf'],data['lfstatus_f_55to59_notinlf'],
               data['lfstatus_f_60to61_notinlf'],data['lfstatus_f_62to64_notinlf'],data['lfstatus_f_65to69_notinlf'],
               data['lfstatus_f_70to74_notinlf'],data['lfstatus_f_75andolder_notinlf']]
data['Employment:Not in Labor Force'] = sum(notinlf)
civemployed = [data['lfstatus_m_16to19_inlf_civilian_employed'],data['lfstatus_m_20to21_inlf_civilian_employed'],data['lfstatus_m_22to24_inlf_civilian_employed'],
               data['lfstatus_m_25to29_inlf_civilian_employed'],data['lfstatus_m_30to34_inlf_civilian_employed'],data['lfstatus_m_35to44_inlf_civilian_employed'],
               data['lfstatus_m_45to54_inlf_civilian_employed'],data['lfstatus_m_55to59_inlf_civilian_employed'],data['lfstatus_m_60to61_inlf_civilian_employed'],
               data['lfstatus_m_62to64_inlf_civilian_employed'],data['lfstatus_m_65to69_inlf_employed'],data['lfstatus_m_70to74_inlf_employed'],
               data['lfstatus_m_75andolder_inlf_employed'],
               data['lfstatus_f_16to19_inlf_civilian_employed'],data['lfstatus_f_20to21_inlf_civilian_employed'],
               data['lfstatus_f_22to24_inlf_civilian_employed'],data['lfstatus_f_25to29_inlf_civilian_employed'],data['lfstatus_f_30to34_inlf_civilian_employed'],
               data['lfstatus_f_35to44_inlf_civilian_employed'],data['lfstatus_f_45to54_inlf_civilian_employed'],data['lfstatus_f_55to59_inlf_civilian_employed'],
               data['lfstatus_f_60to61_inlf_civilian_employed'],data['lfstatus_f_62to64_inlf_civilian_employed'],data['lfstatus_f_65to69_inlf_employed'],
               data['lfstatus_f_70to74_inlf_employed'],data['lfstatus_f_75andolder_inlf_employed']]
data['Employment:Employed Civilian'] = sum(civemployed)
civunemployed = [data['lfstatus_m_16to19_inlf_civilian_unemployed'],data['lfstatus_m_20to21_inlf_civilian_unemployed'],data['lfstatus_m_22to24_inlf_civilian_unemployed'],
               data['lfstatus_m_25to29_inlf_civilian_unemployed'],data['lfstatus_m_30to34_inlf_civilian_unemployed'],data['lfstatus_m_35to44_inlf_civilian_unemployed'],
               data['lfstatus_m_45to54_inlf_civilian_unemployed'],data['lfstatus_m_55to59_inlf_civilian_unemployed'],data['lfstatus_m_60to61_inlf_civilian_unemployed'],
               data['lfstatus_m_62to64_inlf_civilian_unemployed'],data['lfstatus_m_65to69_inlf_unemployed'],data['lfstatus_m_70to74_inlf_unemployed'],
               data['lfstatus_m_75andolder_inlf_unemployed'],
               data['lfstatus_f_16to19_inlf_civilian_unemployed'],data['lfstatus_f_20to21_inlf_civilian_unemployed'],
               data['lfstatus_f_22to24_inlf_civilian_unemployed'],data['lfstatus_f_25to29_inlf_civilian_unemployed'],data['lfstatus_f_30to34_inlf_civilian_unemployed'],
               data['lfstatus_f_35to44_inlf_civilian_unemployed'],data['lfstatus_f_45to54_inlf_civilian_unemployed'],data['lfstatus_f_55to59_inlf_civilian_unemployed'],
               data['lfstatus_f_60to61_inlf_civilian_unemployed'],data['lfstatus_f_62to64_inlf_civilian_unemployed'],data['lfstatus_f_65to69_inlf_unemployed'],
               data['lfstatus_f_70to74_inlf_unemployed'],data['lfstatus_f_75andolder_inlf_unemployed']]
data['Employment:Unemployed Civilian'] = sum(civunemployed)

seriestotalLF = data['lfstatus_total_sexbyagebyemploymentstatus16+_series']
civtotalemployment = data['Employment:Unemployed Civilian'] + data['Employment:Employed Civilian']
civtotal = data['Employment:Unemployed Civilian'] + data['Employment:Employed Civilian'] + data['Employment:Not in Labor Force']
totalemployment = data['Employment:Unemployed Civilian'] + data['Employment:Employed Civilian'] + data['Employment:Armed Forces']

data['Employment%:Civilian Population in LF 16 Over that are Employed'] = percent(data['Employment:Employed Civilian'], civtotalemployment)
data['Employment%:Total Civilian Population 16 Over that are Employed'] = percent(data['Employment:Employed Civilian'], civtotal)
data['Employment%:Population 16 Over in LF that are Employed'] = percent(data['Employment:Employed Civilian'], totalemployment)
data['Employment%:Population 16 Over that are Employed Civilians'] = percent(data['Employment:Employed Civilian'], seriestotalLF)

data['Employment%:Civilian Population in LF 16 Over that are Unemployed'] = percent(data['Employment:Unemployed Civilian'], civtotalemployment)
data['Employment%:Total Civilian Population 16 Over that are Unemployed'] = percent(data['Employment:Unemployed Civilian'], civtotal)
data['Employment%:Population 16 Over in LF that are Unemployed'] = percent(data['Employment:Unemployed Civilian'], totalemployment)
data['Employment%:Population 16 Over that are Unemployed Civilians'] = percent(data['Employment:Unemployed Civilian'], seriestotalLF)

data['Employment%:Civilian Population 16 Over Not in Labor Force'] = percent(data['Employment:Not in Labor Force'], civtotal)
data['Employment%:Total Population 16 Over Not in Labor Force'] = percent(data['Employment:Not in Labor Force'], seriestotalLF)

data['Employment:Total Population 16 Over In Labor Force'] = seriestotalLF - data['Employment:Not in Labor Force']
data['Employment%:Total Population 16 Over In Labor Force'] = percent(data['Employment:Total Population 16 Over In Labor Force'], seriestotalLF)
data['Employment:Civilian Population 16 Over In Labor Force'] = civtotal - data['Employment:Not in Labor Force']
data['Employment%:Civilian Population 16 Over In Labor Force'] = percent(data['Employment:Civilian Population 16 Over In Labor Force'], civtotal)

data['Employment%:Population 16 Over in LF Employed in Armed Forces'] = percent(data['Employment:Armed Forces'], totalemployment)
data['Employment%:Population 16 Over Employed in Armed Forces'] = percent(data['Employment:Armed Forces'], seriestotalLF)

#median household income by householder age
data['HHIncome:Median for Householder Under 25'] = data['hhincome_median_hholderu25']
data['HHIncome:Median for Householder Under 25 to 44'] = data['hhincome_median_hholder25to44']
data['HHIncome:Median for Householder Under 45 to 64'] = data['hhincome_median_hholder45to64']
data['HHIncome:Median for Householder Under 65 Over'] = data['hhincome_median_hholder65over']
#median hh income
data['Median Household Income'] = data['hhincome_median']
#hh income brackets
data['HHIncome:Total Households'] = data['hhincome_total_series']
data['HHIncome:Less than 10,000'] = data['hhincome_lessthan10000']
data['HHIncome%:Less than 10,000'] = percent(data['HHIncome:Less than 10,000'], data['HHIncome:Total Households'])
data['HHIncome:10 to 14,999'] = data['hhincome_10to14999']
data['HHIncome%:10 to 14,999'] = percent(data['HHIncome:10 to 14,999'], data['HHIncome:Total Households'])
data['HHIncome:15 to 19,999'] = data['hhincome_15to19999']
data['HHIncome%:15 to 19,999'] = percent(data['HHIncome:15 to 19,999'], data['HHIncome:Total Households'])
data['HHIncome:20 to 24,999'] = data['hhincome_20to24999']
data['HHIncome%:20 to 24,999'] = percent(data['HHIncome:20 to 24,999'], data['HHIncome:Total Households'])
data['HHIncome:25 to 29,999'] = data['hhincome_25to29999']
data['HHIncome%:25 to 29,999'] = percent(data['HHIncome:25 to 29,999'], data['HHIncome:Total Households'])
data['HHIncome:30 to 34,999'] = data['hhincome_30to34999']
data['HHIncome:%30 to 34,999'] = percent(data['HHIncome:30 to 34,999'], data['HHIncome:Total Households'])
data['HHIncome:35 to 39,999'] = data['hhincome_35to39999']
data['HHIncome%:35 to 39,999'] = percent(data['HHIncome:35 to 39,999'], data['HHIncome:Total Households'])
data['HHIncome:40 to 44,999'] = data['hhincome_40to44999']
data['HHIncome%:40 to 44,999'] = percent(data['HHIncome:40 to 44,999'], data['HHIncome:Total Households'])
data['HHIncome:45 to 49,999'] = data['hhincome_45to49999']
data['HHIncome%:45 to 49,999'] = percent(data['HHIncome:45 to 49,999'], data['HHIncome:Total Households'])
data['HHIncome:50 to 59,999'] = data['hhincome_50to59999']
data['HHIncome%:50 to 59,999'] = percent(data['HHIncome:50 to 59,999'], data['HHIncome:Total Households'])
data['HHIncome:60 to 74,999'] = data['hhincome_60to74999']
data['HHIncome%:60 to 74,999'] = percent(data['HHIncome:60 to 74,999'], data['HHIncome:Total Households'])
data['HHIncome:75 to 99,999'] = data['hhincome_75to99999']
data['HHIncome%:75 to 99,999'] = percent(data['HHIncome:75 to 99,999'], data['HHIncome:Total Households'])
data['HHIncome:100 to 124,999'] = data['hhincome_100to124999']
data['HHIncome%:100 to 124,999'] = percent(data['HHIncome:100 to 124,999'], data['HHIncome:Total Households'])
data['HHIncome:125 to 149,999'] = data['hhincome125to149999']
data['HHIncome%:125 to 149,999'] = percent(data['HHIncome:125 to 149,999'], data['HHIncome:Total Households'])
data['HHIncome:150 to 199,999'] = data['hhincome150to199999']
data['HHIncome%:150 to 199,999'] = percent(data['HHIncome:150 to 199,999'], data['HHIncome:Total Households'])
data['HHIncome:200K or More'] = data['hhincome200ormore']
data['HHIncome%:200K or More'] = percent(data['HHIncome:200K or More'], data['HHIncome:Total Households'])

#earnings
#less than $5,000
thelist = [data['earn_m_1to2499orloss'], data['earn_m_2500to4999'], data['earn_f_1to2499orloss'], data['earn_f_2500to4999']]
data['Earnings:Less than 5,000'] = sum(thelist)
data['Earnings:% Less than 5,000'] = percent(data['Earnings:Less than 5,000'], data['earn_total_series'])
#5-10
thelist = [data['earn_m_5000to7499'], data['earn_m_7500to9999'], data['earn_f_5000to7499'], data['earn_f_7500to9999']]
data['Earnings:5,000 to 9,999'] = sum(thelist)
data['Earnings:% 5,000 to 9,999'] = percent(data['Earnings:5,000 to 9,999'], data['earn_total_series'])
#less than $10,000
lessthan10000 = [data['earn_m_1to2499orloss'], data['earn_m_2500to4999'], data['earn_m_5000to7499'], data['earn_m_7500to9999'], 
                 data['earn_f_1to2499orloss'], data['earn_f_2500to4999'], data['earn_f_5000to7499'], data['earn_f_7500to9999']]              
data['Earnings:Less than 10,000'] = sum(lessthan10000)
data['Earnings:% Less than 10,000'] = percent(data['Earnings:Less than 10,000'], data['earn_total_series'])
#10to20
thelist = [data['earn_m_10000to12499'], data['earn_m_12500to14999'], data['earn_m_15000to17499'], data['earn_m_17500to19999'], data['earn_f_10000to12499'],
           data['earn_f_12500to14999'], data['earn_f_15000to17499'], data['earn_f_17500to19999']]
data['Earnings:10,000 to 19,999'] = sum(thelist)
data['Earnings:% 10,000 to 19,999'] = percent(data['Earnings:10,000 to 19,999'], data['earn_total_series'])
#20to30
thelist = [data['earn_m_20000to22499'],data['earn_m_22500to24999'], data['earn_m_25000to29999'], 
           data['earn_f_20000to22499'], data['earn_f_22500to24999'], data['earn_f_25000to29999']]
data['Earnings:20,000 to 29,999'] = sum(thelist)
data['Earnings:% 20,000 to 29,999'] = percent(data['Earnings:20,000 to 29,999'], data['earn_total_series'])
#30to40
thelist = [data['earn_m_30000to34999'], data['earn_m_35000to39999'], 
           data['earn_f_30000to34999'], data['earn_f_35000to39999']]
data['Earnings:30,000 to 39,999'] = sum(thelist)
data['Earnings:% 30,000 to 39,999'] = percent(data['Earnings:30,000 to 39,999'], data['earn_total_series'])
#40to50
thelist = [data['earn_m_40000to44999'], data['earn_m_45000to49999'], 
           data['earn_f_40000to44999'], data['earn_f_45000to49999']]
data['Earnings:40,000 to 49,999'] = sum(thelist)
data['Earnings:% 40,000 to 49,999'] = percent(data['Earnings:40,000 to 49,999'], data['earn_total_series'])
#50to65
thelist = [data['earn_m_50000to54999'], data['earn_m_55000to64999'], 
           data['earn_f_50000to54999'], data['earn_f_55000to64999']]
data['Earnings:50,000 to 64,999'] = sum(thelist)
data['Earnings:% 50,000 to 64,999'] = percent(data['Earnings:50,000 to 64,999'], data['earn_total_series'])
#65to75
thelist = [data['earn_m_65000to74999'], data['earn_f_65000to74999']]
data['Earnings:65,000 to 74,999'] = sum(thelist)
data['Earnings:% 65,000 to 74,999'] = percent(data['Earnings:65,000 to 74,999'], data['earn_total_series'])

#less than $25,000
lessthan25 = [data['earn_m_1to2499orloss'], data['earn_m_2500to4999'], data['earn_m_5000to7499'], data['earn_m_7500to9999'], data['earn_m_10000to12499'],
              data['earn_m_12500to14999'], data['earn_m_15000to17499'], data['earn_m_17500to19999'], data['earn_m_20000to22499'],data['earn_m_22500to24999'], 
              data['earn_f_1to2499orloss'], data['earn_f_2500to4999'], data['earn_f_5000to7499'], data['earn_f_7500to9999'], data['earn_f_10000to12499'],
              data['earn_f_12500to14999'], data['earn_f_15000to17499'], data['earn_f_17500to19999'], data['earn_f_20000to22499'], data['earn_f_22500to24999']]
data['Earnings:Less than 25,000'] = sum(lessthan25)
data['Earnings:% Less than 25,000'] = percent(data['Earnings:Less than 25,000'], data['earn_total_series'])
#$25,000 to $49,999
twenty5000to49999 = [data['earn_m_25000to29999'], data['earn_m_30000to34999'], data['earn_m_35000to39999'], data['earn_m_40000to44999'],
                     data['earn_m_45000to49999'], data['earn_f_25000to29999'], data['earn_f_30000to34999'], data['earn_f_35000to39999'],
                     data['earn_f_40000to44999'], data['earn_f_45000to49999']]
data['Earnings:25,000 to 49,999'] = sum(twenty5000to49999)
data['Earnings:% 25,000 to 49,999'] = percent(data['Earnings:25,000 to 49,999'], data['earn_total_series'])
#$50,000 to $74,000
fifty000to74999 = [data['earn_m_50000to54999'], data['earn_m_55000to64999'], data['earn_m_65000to74999'],
                   data['earn_f_50000to54999'], data['earn_f_55000to64999'], data['earn_f_65000to74999']]
data['Earnings:50,000 to 74,999'] = sum(fifty000to74999)
data['Earnings:% 50,000 to 74,999'] = percent(data['Earnings:50,000 to 74,999'], data['earn_total_series'])
#$75,000 to $99,999
seventy5000to99999 = [data['earn_m_75000to99999'], data['earn_f_75000to99999']]
data['Earnings:75,000 to 99,999'] = sum(seventy5000to99999)
data['Earnings:% 75,000 to 99,999'] = percent(data['Earnings:75,000 to 99,999'], data['earn_total_series'])
#$100,000+
onehundred000up = [data['earn_m_100000ormore'], data['earn_f_100000ormore']]
data['Earnings:100,000 and Over'] = sum(onehundred000up)
data['Earnings:% 100,000 and Over'] = percent(data['Earnings:100,000 and Over'], data['earn_total_series'])

data['Earnings:Median, All Earners'] = data['earn_allwithearnings_median']

#earnings for full time year-round workers
thelist = [data['earn_total_fulltime_m'], data['earn_total_fulltime_f']]
earnfulltimetotalseries = sum(thelist)
#less than $5,000
thelist = [data['earn_m_fulltime_1to2499orloss'], data['earn_m_fulltime_2500to4999'], data['earn_f_fulltime_1to2499orloss'], data['earn_f_fulltime_2500to4999']]
data['EarningsFT:Less than 5,000'] = sum(thelist)
data['EarningsFT:% Less than 5,000'] = percent(data['EarningsFT:Less than 5,000'], earnfulltimetotalseries)
#5-10
thelist = [data['earn_m_fulltime_5000to7499'], data['earn_m_fulltime_7500to9999'], data['earn_f_fulltime_5000to7499'], data['earn_f_fulltime_7500to9999']]
data['EarningsFT:5,000 to 9,999'] = sum(thelist)
data['EarningsFT:% 5,000 to 9,999'] = percent(data['EarningsFT:5,000 to 9,999'], earnfulltimetotalseries)
#less than $10,000
lessthan10000 = [data['earn_m_fulltime_1to2499orloss'], data['earn_m_fulltime_2500to4999'], data['earn_m_fulltime_5000to7499'], data['earn_m_fulltime_7500to9999'], 
                 data['earn_f_fulltime_1to2499orloss'], data['earn_f_fulltime_2500to4999'], data['earn_f_fulltime_5000to7499'], data['earn_f_fulltime_7500to9999']]              
data['EarningsFT:Less than 10,000'] = sum(lessthan10000)
data['EarningsFT:% Less than 10,000'] = percent(data['EarningsFT:Less than 10,000'], earnfulltimetotalseries)
#10to20
thelist = [data['earn_m_fulltime_10000to12499'], data['earn_m_fulltime_12500to14999'], data['earn_m_fulltime_15000to17499'], data['earn_m_fulltime_17500to19999'], data['earn_f_fulltime_10000to12499'],
           data['earn_f_fulltime_12500to14999'], data['earn_f_fulltime_15000to17499'], data['earn_f_fulltime_17500to19999']]
data['EarningsFT:10,000 to 19,999'] = sum(thelist)
data['EarningsFT:% 10,000 to 19,999'] = percent(data['EarningsFT:10,000 to 19,999'], earnfulltimetotalseries)
#20to30
thelist = [data['earn_m_fulltime_20000to22499'],data['earn_m_fulltime_22500to24999'], data['earn_m_fulltime_25000to29999'], 
           data['earn_f_fulltime_20000to22499'], data['earn_f_fulltime_22500to24999'], data['earn_f_fulltime_25000to29999']]
data['EarningsFT:20,000 to 29,999'] = sum(thelist)
data['EarningsFT:% 20,000 to 29,999'] = percent(data['EarningsFT:20,000 to 29,999'], earnfulltimetotalseries)
#30to40
thelist = [data['earn_m_fulltime_30000to34999'], data['earn_m_fulltime_35000to39999'], 
           data['earn_f_fulltime_30000to34999'], data['earn_f_fulltime_35000to39999']]
data['EarningsFT:30,000 to 39,999'] = sum(thelist)
data['EarningsFT:% 30,000 to 39,999'] = percent(data['EarningsFT:30,000 to 39,999'], earnfulltimetotalseries)
#40to50
thelist = [data['earn_m_fulltime_40000to44999'], data['earn_m_fulltime_45000to49999'], 
           data['earn_f_fulltime_40000to44999'], data['earn_f_fulltime_45000to49999']]
data['EarningsFT:40,000 to 49,999'] = sum(thelist)
data['EarningsFT:% 40,000 to 49,999'] = percent(data['EarningsFT:40,000 to 49,999'], earnfulltimetotalseries)
#50to65
thelist = [data['earn_m_fulltime_50000to54999'], data['earn_m_fulltime_55000to64999'], 
           data['earn_f_fulltime_50000to54999'], data['earn_f_fulltime_55000to64999']]
data['EarningsFT:50,000 to 64,999'] = sum(thelist)
data['EarningsFT:% 50,000 to 64,999'] = percent(data['EarningsFT:50,000 to 64,999'], earnfulltimetotalseries)
#65to75
thelist = [data['earn_m_fulltime_65000to74999'], data['earn_f_fulltime_65000to74999']]
data['EarningsFT:65,000 to 74,999'] = sum(thelist)
data['EarningsFT:% 65,000 to 74,999'] = percent(data['EarningsFT:65,000 to 74,999'], earnfulltimetotalseries)

#less than $25,000
lessthan25 = [data['earn_m_fulltime_1to2499orloss'], data['earn_m_fulltime_2500to4999'], data['earn_m_fulltime_5000to7499'], 
              data['earn_m_fulltime_7500to9999'], data['earn_m_fulltime_10000to12499'],
              data['earn_m_fulltime_12500to14999'], data['earn_m_fulltime_15000to17499'], data['earn_m_fulltime_17500to19999'], 
              data['earn_m_fulltime_20000to22499'],data['earn_m_fulltime_22500to24999'], 
              data['earn_f_fulltime_1to2499orloss'], data['earn_f_fulltime_2500to4999'], data['earn_f_fulltime_5000to7499'], 
              data['earn_f_fulltime_7500to9999'], data['earn_f_fulltime_10000to12499'],
              data['earn_f_fulltime_12500to14999'], data['earn_f_fulltime_15000to17499'], data['earn_f_fulltime_17500to19999'], 
              data['earn_f_fulltime_20000to22499'], data['earn_f_fulltime_22500to24999']]
data['EarningsFT:Less than 25,000'] = sum(lessthan25)
data['EarningsFT:% Less than 25,000'] = percent(data['EarningsFT:Less than 25,000'], earnfulltimetotalseries)
#$25,000 to $49,999
twenty5000to49999 = [data['earn_m_fulltime_25000to29999'], data['earn_m_fulltime_30000to34999'], data['earn_m_fulltime_35000to39999'], 
                     data['earn_m_fulltime_40000to44999'], data['earn_m_fulltime_45000to49999'], data['earn_f_fulltime_25000to29999'], 
                     data['earn_f_fulltime_30000to34999'], data['earn_f_fulltime_35000to39999'],
                     data['earn_f_fulltime_40000to44999'], data['earn_f_fulltime_45000to49999']]
data['EarningsFT:25,000 to 49,999'] = sum(twenty5000to49999)
data['EarningsFT:% 25,000 to 49,999'] = percent(data['EarningsFT:25,000 to 49,999'], earnfulltimetotalseries)
#$50,000 to $74,000
fifty000to74999 = [data['earn_m_fulltime_50000to54999'], data['earn_m_fulltime_55000to64999'], data['earn_m_fulltime_65000to74999'],
                   data['earn_f_fulltime_50000to54999'], data['earn_f_fulltime_55000to64999'], data['earn_f_fulltime_65000to74999']]
data['EarningsFT:50,000 to 74,999'] = sum(fifty000to74999)
data['EarningsFT:% 50,000 to 74,999'] = percent(data['EarningsFT:50,000 to 74,999'], earnfulltimetotalseries)
#$75,000 to $99,999
seventy5000to99999 = [data['earn_m_fulltime_75000to99999'], data['earn_f_fulltime_75000to99999']]
data['EarningsFT:75,000 to 99,999'] = sum(seventy5000to99999)
data['EarningsFT:% 75,000 to 99,999'] = percent(data['EarningsFT:75,000 to 99,999'], earnfulltimetotalseries)
#$100,000+
onehundred000up = [data['earn_m_fulltime_100000ormore'], data['earn_f_fulltime_100000ormore']]
data['EarningsFT:100,000 and Over'] = sum(onehundred000up)
data['EarningsFT:% 100,000 and Over'] = percent(data['EarningsFT:100,000 and Over'], earnfulltimetotalseries)


#median gross rent
data['Median Gross Rent'] = data['housingcost_mediangrossrent_renteroccupied']
#median monthly owner costs
data['Median Monthly Owner Costs'] = data['housingcost_medcosts_ownerocc']
data['Median Monthly Owner Costs Home with Mortgage'] = data['housingcost_medcosts_ownerocc_mortgage']
data['Median Monthly Owner Costs Home without Mortgage'] = data['housingcost_medcosts_ownerocc_womortgage']

data['Commute:Workers 16+ Not Working at Home'] = data['traveltimemode_series_total']  
data['Commute:Less than 10 Minutes'] = data['traveltimemode_lessthan10']
data['Commute%:Less than 10 Minutes'] = percent(data['traveltimemode_lessthan10'], data['Commute:Workers 16+ Not Working at Home'])
data['Commute:10 to 14 Minutes'] = data['traveltimemode_10to14']
data['Commute%:10 to 14 Minutes'] = percent(data['traveltimemode_10to14'], data['Commute:Workers 16+ Not Working at Home'])
data['Commute:15 to 19 Minutes'] = data['traveltimemode_15to19']
data['Commute%:15 to 19 Minutes'] = percent(data['traveltimemode_15to19'], data['Commute:Workers 16+ Not Working at Home'])
data['Commute:20 to 24 Minutes'] = data['traveltimemode_20to24']
data['Commute%:20 to 24 Minutes'] = percent(data['traveltimemode_20to24'], data['Commute:Workers 16+ Not Working at Home'])
data['Commute:25 to 29 Minutes'] = data['traveltimemode_25to29']
data['Commute%:25 to 29 Minutes'] = percent(data['traveltimemode_25to29'], data['Commute:Workers 16+ Not Working at Home'])
data['Commute:30 to 34 Minutes'] = data['traveltimemode_30to34']
data['Commute%:30 to 34 Minutes'] = percent(data['traveltimemode_30to34'], data['Commute:Workers 16+ Not Working at Home'])
data['Commute:35 to 44 Minutes'] = data['traveltimemode_35to44']
data['Commute%:35 to 44 Minutes'] = percent(data['traveltimemode_35to44'], data['Commute:Workers 16+ Not Working at Home'])
data['Commute:45 to 59 Minutes'] = data['traveltimemode_45to59']
data['Commute%:45 to 59 Minutes'] = percent(data['traveltimemode_45to59'], data['Commute:Workers 16+ Not Working at Home'])
data['Commute:60 or More Minutes'] = data['traveltimemode_60ormore']
data['Commute%:60 or More Minutes'] = percent(data['traveltimemode_60ormore'], data['Commute:Workers 16+ Not Working at Home'])
data['Commute:45 or More Minutes'] = data['traveltimemode_45to59'] + data['traveltimemode_60ormore']
data['Commute%:45 or More Minutes'] = percent(data['Commute:45 or More Minutes'], data['Commute:Workers 16+ Not Working at Home'])

#means of transportation to work
data['Transpo:Workers Commuting'] = data['commute_total_meansoftransportationtowork_series']
data['Transpo:Car, Truck, or Van'] = data['commute_cartruckvan']
data['Transpo%:Car, Truck, or Van'] = percent(data['Transpo:Car, Truck, or Van'],data['Transpo:Workers Commuting'])

data['Transpo:Car, Truck, or Van:Drove Alone'] = data['commute_cartruckvan_drovealone']
data['Transpo%:Car, Truck, or Van:Drove Alone'] = percent(data['Transpo:Car, Truck, or Van:Drove Alone'],data['Transpo:Workers Commuting'])
data['Transpo%:Car, Truck, or Van:Drove Alone Share of Drivers'] = percent(data['Transpo:Car, Truck, or Van:Drove Alone'],data['Transpo:Car, Truck, or Van'])

data['Transpo:Car, Truck, or Van:Carpooled'] = data['commute_cartruckvan_carpooled']
data['Transpo%:Car, Truck, or Van:Carpooled'] = percent(data['Transpo:Car, Truck, or Van:Carpooled'],data['Transpo:Workers Commuting'])
data['Transpo%:Car, Truck, or Van:Carpooled'] = percent(data['Transpo:Car, Truck, or Van:Carpooled'],data['Transpo:Car, Truck, or Van'])


data['Transpo:Public Transportation'] = data['commute_publictransportation']
data['Transpo%:Public Transportation'] = percent(data['Transpo:Public Transportation'],data['Transpo:Workers Commuting'])
data['Transpo:Bicycle'] = data['commute_bicycle']
data['Transpo%:Bicycle'] = percent(data['Transpo:Bicycle'],data['Transpo:Workers Commuting'])
data['Transpo:Walk'] = data['commute_walk']
data['Transpo%:Walk'] = percent(data['Transpo:Walk'],data['Transpo:Workers Commuting'])
data['Transpo:Worked From Home'] = data['commute_workedfromhome']
data['Transpo%:Worked From Home'] = percent(data['Transpo:Worked From Home'],data['Transpo:Workers Commuting'])
data['Transpo:Taxi, Motorcycle, Other'] = data['commute_taxicabmotorcycleother']
data['Transpo%:Taxi, Motorcycle, Other'] = percent(data['Transpo:Taxi, Motorcycle, Other'],data['Transpo:Workers Commuting'])

#cost burden
data['CB:Total Housing Units'] = data['housingcost_total_selectedownercosts%hhincome_series']+data['housingcost_total_rent%hhincome_series']
allcostburden = [data['housingcost_%ownercost30to34.9_wmortgage'],data['housingcost_%ownercost35to39.9_wmortgage'],data['housingcost_%ownercost40to49.9_wmortgage'],
                 data['housingcost_%ownercost50+_wmortgage'],data['housingcost_%ownercost30to34.9_womortgage'],data['housingcost_%ownercost35to39.9_womortgage'],
                 data['housingcost_%ownercost40to49.9_womortgage'],data['housingcost_%ownercost50+_womortgage'],data['housingcost_%rentercost30to34.9'],
                 data['housingcost_%rentercost35to39.9'],data['housingcost_%rentercost40to49.9'],data['housingcost_%rentercost50+']]
data['CB:Cost Burdened Households'] = sum(allcostburden)
data['CB:Renter Occupied Units'] = data['housingcost_total_rent%hhincome_series']
rentercostburden = [data['housingcost_%rentercost30to34.9'],data['housingcost_%rentercost35to39.9'],
                    data['housingcost_%rentercost40to49.9'],data['housingcost_%rentercost50+']]
data['CB:Cost Burdened Renters'] = sum(rentercostburden)
data['CB%:Cost Burdened Renters'] = percent(data['CB:Cost Burdened Renters'], data['CB:Renter Occupied Units'])
data['CB:Owner Occupied Units'] = data['housingcost_total_selectedownercosts%hhincome_series']
ownercostburden = [data['housingcost_%ownercost30to34.9_wmortgage'],data['housingcost_%ownercost35to39.9_wmortgage'],data['housingcost_%ownercost40to49.9_wmortgage'],
                   data['housingcost_%ownercost50+_wmortgage'],data['housingcost_%ownercost30to34.9_womortgage'],data['housingcost_%ownercost35to39.9_womortgage'],
                   data['housingcost_%ownercost40to49.9_womortgage'],data['housingcost_%ownercost50+_womortgage']]
data['CB:Cost Burdened Homeowners'] = sum(ownercostburden)
data['CB%: Cost Burdened Homeowners'] = percent(data['CB:Cost Burdened Homeowners'], data['CB:Owner Occupied Units'])
severecostburden = [data['housingcost_%ownercost50+_womortgage'],data['housingcost_%ownercost50+_wmortgage'],data['housingcost_%rentercost50+']]
data['CB:Severe Cost Burdened Households'] = sum(severecostburden)
data['CB%:Severe Cost Burdened Households'] = percent(data['CB:Severe Cost Burdened Households'],data['CB:Total Housing Units'])
ownerseverecostburden = [data['housingcost_%ownercost50+_womortgage'],data['housingcost_%ownercost50+_wmortgage']]
data['CB:Severe Cost Burdened Homeowners'] = sum(ownerseverecostburden)
data['CB%:Severe Cost Burdened Homeowners'] = percent(data['CB:Severe Cost Burdened Homeowners'],data['CB:Owner Occupied Units'])
renterseverecostburden = [data['housingcost_%rentercost50+']]
data['CB:Severe Cost Burdened Renters'] = sum(renterseverecostburden)
data['CB%:Severe Cost Burdened Renters'] = percent(data['CB:Severe Cost Burdened Renters'],data['CB:Renter Occupied Units'])
#add-ons
data['CB%:Cost Burdened Households'] = percent(data['CB:Cost Burdened Households'], data['CB:Total Housing Units'])
data['CB%:Cost Burdened Households Homeowners'] = percent(data['CB:Cost Burdened Homeowners'], data['CB:Cost Burdened Households'])
data['CB%:Cost Burdened Households Renters'] = percent(data['CB:Cost Burdened Renters'], data['CB:Cost Burdened Households'])
data['CB%:Severe Cost Burdened Households Homeowners'] = percent(data['CB:Severe Cost Burdened Homeowners'], data['CB:Severe Cost Burdened Households'])
data['CB%:Severe Cost Burdened Households Renters'] = percent(data['CB:Severe Cost Burdened Renters'], data['CB:Severe Cost Burdened Households'])

data['Average Travel Time to Work'] = data['aggregatetraveltimetowork']/data['Commute:Workers 16+ Not Working at Home']
data['Median Home Value for Owner Occupied Units'] = data['housing_medianvalue']
#poverty
data['Poverty:Population for Whom Poverty Status is Determined'] = data['poverty_total_bysexbyage_series']
data['Poverty: Population Below Poverty Level'] = data['poverty_belowlevel']
data['Poverty%: Below Poverty Level'] = percent(data['Poverty: Population Below Poverty Level'], data['Poverty:Population for Whom Poverty Status is Determined'])

In [19]:
cols = coldropper.columns
data = data.drop(columns = cols)

In [20]:
# data = data.set_index('NAME').transpose()
# #make sure there is no erroneus median or average data for aggregated regions
# region_cols = ['GNRC', 'GNRC Region', 'MPO', 'Rutherford Incorporated', 'Rutherford Unincorporated', 'Wilson Incorporated', 'Wilson Unincorporated', 
#                'Cheatham Incorporated', 'Cheatham Unincorporated', 'Dickson Incorporated', 'Dickson Unincorporated', 'Humphreys Incorporated', 
#                'Humphreys Unincorporated', 'Montgomery Incorporated', 'Montgomery Unincorporated']
# data.loc[data.index.str.contains('Median', case = False), region_cols] = 0
# data.loc[data.index.str.contains('Average', case = False), region_cols] = 0

In [21]:
# data = data.transpose().reset_index(drop = False)

In [22]:
#make sure numerical data is float datatype
cols = list(data.columns)
cols.remove('NAME')
cols.remove('GEO_ID')
data[cols] = data[cols].astype(float)

In [23]:
len(data.columns)

209

In [24]:
# #final check
data.head(3)

,NAME,GEO_ID,Ed:Population 25+ Educational Attainment,Ed:Less than High School,Ed%:Less than High School,Ed:High School Graduate or Equivalency,Ed%:High School Graduate or Equivalency,Ed:High School Graduate or More,Ed%:High School Graduate or More,Ed:Some College,Ed%:Some College,Ed%:Some College or More,Ed:Associates,Ed%:Associates,Ed:Bachelors,Ed%:Bachelors,Ed:Bachelors or More,Ed%:Bachelors or More,Ed:Masters,Ed:Masters or More,Ed%:Masters or More,Ed%:Masters,Ed:Professional School Degree,Ed%:Professional School Degree,Ed%:Professional School Degree or More,Ed:Doctorate Degree,Ed%:Doctorate Degree,Employment:Armed Forces,Employment:Not in Labor Force,Employment:Employed Civilian,Employment:Unemployed Civilian,Employment%:Civilian Population in LF 16 Over that are Employed,Employment%:Total Civilian Population 16 Over that are Employed,Employment%:Population 16 Over in LF that are Employed,Employment%:Population 16 Over that are Employed Civilians,Employment%:Civilian Population in LF 16 Over that are Unemployed,Employment%:Total Civilian Population 16 Over that are Unemployed,Employment%:Population 16 Over in LF that are Unemployed,Employment%:Population 16 Over that are Unemployed Civilians,Employment%:Civilian Population 16 Over Not in Labor Force,Employment%:Total Population 16 Over Not in Labor Force,Employment:Total Population 16 Over In Labor Force,Employment%:Total Population 16 Over In Labor Force,Employment:Civilian Population 16 Over In Labor Force,Employment%:Civilian Population 16 Over In Labor Force,Employment%:Population 16 Over in LF Employed in Armed Forces,Employment%:Population 16 Over Employed in Armed Forces,HHIncome:Median for Householder Under 25,HHIncome:Median for Householder Under 25 to 44,HHIncome:Median for Householder Under 45 to 64,HHIncome:Median for Householder Under 65 Over,Median Household Income,HHIncome:Total Households,"HHIncome:Less than 10,000","HHIncome%:Less than 10,000","HHIncome:10 to 14,999","HHIncome%:10 to 14,999","HHIncome:15 to 19,999","HHIncome%:15 to 19,999","HHIncome:20 to 24,999","HHIncome%:20 to 24,999","HHIncome:25 to 29,999","HHIncome%:25 to 29,999","HHIncome:30 to 34,999","HHIncome:%30 to 34,999","HHIncome:35 to 39,999","HHIncome%:35 to 39,999","HHIncome:40 to 44,999","HHIncome%:40 to 44,999","HHIncome:45 to 49,999","HHIncome%:45 to 49,999","HHIncome:50 to 59,999","HHIncome%:50 to 59,999","HHIncome:60 to 74,999","HHIncome%:60 to 74,999","HHIncome:75 to 99,999","HHIncome%:75 to 99,999","HHIncome:100 to 124,999","HHIncome%:100 to 124,999","HHIncome:125 to 149,999","HHIncome%:125 to 149,999","HHIncome:150 to 199,999","HHIncome%:150 to 199,999",HHIncome:200K or More,HHIncome%:200K or More,"Earnings:Less than 5,000","Earnings:% Less than 5,000","Earnings:5,000 to 9,999","Earnings:% 5,000 to 9,999","Earnings:Less than 10,000","Earnings:% Less than 10,000","Earnings:10,000 to 19,999","Earnings:% 10,000 to 19,999","Earnings:20,000 to 29,999","Earnings:% 20,000 to 29,999","Earnings:30,000 to 39,999","Earnings:% 30,000 to 39,999","Earnings:40,000 to 49,999","Earnings:% 40,000 to 49,999","Earnings:50,000 to 64,999","Earnings:% 50,000 to 64,999","Earnings:65,000 to 74,999","Earnings:% 65,000 to 74,999","Earnings:Less than 25,000","Earnings:% Less than 25,000","Earnings:25,000 to 49,999","Earnings:% 25,000 to 49,999","Earnings:50,000 to 74,999","Earnings:% 50,000 to 74,999","Earnings:75,000 to 99,999","Earnings:% 75,000 to 99,999","Earnings:100,000 and Over","Earnings:% 100,000 and Over","Earnings:Median, All Earners","EarningsFT:Less than 5,000","EarningsFT:% Less than 5,000","EarningsFT:5,000 to 9,999","EarningsFT:% 5,000 to 9,999","EarningsFT:Less than 10,000","EarningsFT:% Less than 10,000","EarningsFT:10,000 to 19,999","EarningsFT:% 10,000 to 19,999","EarningsFT:20,000 to 29,999","EarningsFT:% 20,000 to 29,999","EarningsFT:30,000 to 39,999","EarningsFT:% 30,000 to 39,999","EarningsFT:40,000 to 49,999","EarningsFT:% 40,000 to 49,999","EarningsFT:50,000 to 64,999","EarningsFT:% 50,000 to 64,999","EarningsFT:65,000 to 74,999","EarningsFT:% 65,000 to 74,999","EarningsFT:Less than 25,000","EarningsFT:% Less than 25,000","EarningsFT:25,000 to 49,999","EarningsFT:% 25,000 to 49,999","EarningsFT:50,000 to 74,999","EarningsFT:% 50,000 to 74,999","EarningsFT:75,000 to 99,999","EarningsFT:% 75,000 to 99,999","EarningsFT:100,000 and Over","EarningsFT:% 100,000 and Over",Median Gross Rent,Median Monthly Owner Costs,Median Monthly Owner Costs Home with Mortgage,Median Monthly Owner Costs Home without Mortgage,Commute:Workers 16+ Not Working at Home,Commute:Less than 10 Minutes,Commute%:Less than 10 Minutes,Commute:10 to 14 Minutes,Commute%:10 to 14 Minutes,Commute:15 to 19 Minutes,Commute%:15 to 19 Minutes,Commute:20 to 24 Minutes,Commute%:20 to 24 Minutes,Commute:25 to 29 Minutes,Commute%:25 to 29 Minutes,Commute:30 to 34 Minutes,Commute%:30 to 34 Minutes,Commute:35 to 44 Minutes,Commute%:35 to 44 Minutes,Commute:45 to 59 Minutes,Commute%:45 to 59 Minutes,Commute:60 or More Minutes,Commute%:60 or More Minutes,Commute:45 or More Minutes,Commute%:45 or More Minutes,Transpo:Workers Commuting,"Transpo:Car, Truck, or Van","Transpo%:Car, Truck, or Van","Transpo:Car, Truck, or Van:Drove Alone","Transpo%:Car, Truck, or Van:Drove Alone","Transpo%:Car, Truck, or Van:Drove Alone Share of Drivers","Transpo:Car, Truck, or Van:Carpooled","Transpo%:Car, Truck, or Van:Carpooled",Transpo:Public Transportation,Transpo%:Public Transportation,Transpo:Bicycle,Transpo%:Bicycle,Transpo:Walk,Transpo%:Walk,Transpo:Worked From Home,Transpo%:Worked From Home,"Transpo:Taxi, Motorcycle, Other","Transpo%:Taxi, Motorcycle, Other",CB:Total Housing Units,CB:Cost Burdened Households,CB:Renter Occupied Units,CB:Cost Burdened Renters,CB%:Cost Burdened Renters,CB:Owner Occupied Units,CB:Cost Burdened Homeowners,CB%: Cost Burdened Homeowners,CB:Severe Cost Burdened Households,CB%:Severe Cost Burdened Households,CB:Severe Cost Burdened Homeowners,CB%:Severe Cost Burdened Homeowners,CB:Severe Cost Burdened Renters,CB%:Severe Cost Burdened Renters,CB%:Cost Burdened Households,CB%:Cost Burdened Households Homeowners,CB%:Cost Burdened Households Renters,CB%:Severe Cost Burdened Households Homeowners,CB%:Severe Cost Burdened Households Renters,Average Travel Time to Work,Median Home Value for Owner Occupied Units,Poverty:Population for Whom Poverty Status is Determined,Poverty: Population Below Poverty Level,Poverty%: Below Poverty Level
0,"Sumner County, Tennessee",0500000US47165,116882.0,12555.0,10.741603,37621.0,32.187163,104327.0,89.258397,28208.0,24.133742,49.249671,8575.0,7.336459,20190.0,17.273832,29923.0,25.601034,7107.0,9733.0,8.327202,6.080491,1699.0,1.453603,8.327202,927.0,0.793108,198.0,46284.0,84387.0,4679.0,94.746592,62.347248,94.536431,62.256175,5.253408,3.456963,5.241755,3.451914,34.195789,34.145838,89264.0,65.854162,89066.0,65.804211,0.221814,0.146074,36189.0,63173.0,69950.0,41918.0,58972.0,63240.0,2809.0,4.441809,2397.0,3.790323,2650.0,4.190386,3274.0,5.177103,2603.0,4.116066,3455.0,5.463314,3238.0,5.120177,3331.0,5.267236,2878.0,4.550917,5579.0,8.821948,7158.0,11.318786,8883.0,14.046490,5734.0,9.067046,3143.0,4.969956,3259.0,5.153384,2849.0,4.505060,8979.0,9.670749,6686.0,7.201094,15665.0,16.871843,12273.0,13.218521,14290.0,15.390912,13015.0,14.017685,10026.0,10.798410,10803.0,11.635271,3807.0,4.100294,35409.0,38.136935,29860.0,32.160436,14610.0,15.735565,5830.0,6.279147,7138.0,7.687917,31990.0,202.0,0.328332,628.0,1.020756,830.0,1.349089,5140.0,8.354599,10992.0,17.866489,10924.0,17.755961,8636.0,14.037027,9707.0,15.777839,3554.0,5.776701,11299.0,18.365489,25223.0,40.997676,13261.0,21.554541,5300.0,8.614664,6440.0,10.467630,900.0,1066.0,1360.0,410.0,79003.0,8739.0,11.061605,9935.0,12.575472,10354.0,13.105831,9637.0,12.198271,5230.0,6.620002,11260.0,14.252623,7243.0,9.168006,9484.0,12.004607,7121.0,9.013582,16605.0,21.018189,83075.0,77179.0,92.902799,70241.0,84.551309,91.010508,6938.0,8.989492,391.0,0.470659,70.0,0.084261,571.0,0.687331,4072.0,4.901595,792.0,0.953355,63240.0,17605.0,17103.0,7574.0,44.284628,46137.0,10031.0,21.741769,6656.0,10.524984,3168.0,6.866506,3488.0,20.394083,27.838393,56.978131,43.021869,47.596154,52.403846,27.759515,184900.0,170962.0,16543.0,9.676419
1,"Trousdale County, Tennessee",0500000US47169,5339.0,1105.0,20.696760,2106.0,39.445589,4234.0,79.303240,1024.0,19.179622,32.122120,314.0,5.881251,521.0,9.758382,790.0,14.796778,207.0,269.0,5.038397,3.877131,54.0,1.011425,5.038397,8.0,0.149841,0.0,2486.0,3530.0,306.0,92.022941,55.836761,92.022941,55.836761,7.977059,4.840240,7.977059,4.840240,39.322999,39.322999,3836.0,60.677001,3836.0,60.677001,0.000000,0.000000,-666666666.0,57214.0,35026.0,53158.0,47667.0,2958.0,242.0,8.181204,239.0,8.079784,140.0,4.732928,201.0,6.795132,312.0,10.547667,23.0,0.777552,158.0,5.341447,82.0,2.772143,110.0,3.718729,334.0,11.291413,249.0,8.417850,435.0,14.705882,229.0,7.741717,83.0,2.805950,103.0,3.482082,18.0,0.608519,390.0,10.015408,349.0,8.962506,739.0,18.977915,683.0,17.539805,843.0,21.648690,422.0,10.837185,235.0,6.034926,518.0,13.302517,60.0,1.540832,1658.0,42.578326,1264.0,32.460195,578.0,14.843349,272.0,6.985105,122.0,3.133025,26741.0,0.0,0.000000,66.0,2.727273,66.0,2.727273,243.0,10.041322,635.0,26.239669,358.0,14.793388,215.0,8.884298,459.0,18.966942,60.0,2.479339,524.0,21.652893,993.0,41.033058,519.0,21.446281,272.0,11.239669,112.0,4.628099,592.0,687.0,1071.0,372.0,3306.0,422.0,12.764670,477.0,14.428312,281.0,8.499698,300.0,9.074410,123.0,3.720508,714.0,21.597096,273.0,8.257713,247.0,7.471264,469.0,14.186328,716.0,21.657592,3467.0,3270.0,94.317854,2872.0,82.838189,87.828746,398.0,12.171254,2.0,0.057687,0.0,0.000000,34.0,0.980675,161.0,4.643784,0.0,0.000000,2958.0,908.0,693.0,267.0,38.528139,2265.0,641.0,28.300221,426.0,14.401623,314.0,13.863135,112.0,16.161616,30.696416,70.594714,29.405286,73.708920,26.291080,28.377193,129100.0,7863.0,1043.0,13.264657
2,"Davidson County, Tennessee",0500000US47037,454177.0,56790.0,12.503936,105806.0,23.296204,397387.0,87.496064,89465.0,19.698267,59.147205,28607.0,6.298646,108196.0,23.822430,173509.0,38.202947,43972.0,65313.0,14.380517,9.681688,12641.0,2.783276,14.380517,8700.0,1.915553,434.0,161005.0,352174.0,23351.0,93.781772,65.639200,93.673512,65.586147,6.218228,4.352226,6.211050,4.348709,30.008574,29.984319,375959.0,70.015681,375525.0,69.991426,0.115438,0.080825,28949.0,52234.0,56652.0,42673.0,50484.0,269078.0,19294.0,7.170412,13523.0,5.025680,13966.0,5.190317,14949.0,5.555638,15003.0,5.575707,15182.0,5.642230,14058.0,5.224507,14506.0,5.391002,12789.0,4.752897,21764.0,8.088361,28131.0,10.454589,31887.0,11.850467,18940.0,7.038851,11068.0,4.113305,11385.0,4.231115,12633.0,4.694921,40854.0,10.455974,27376.0,7.006480,68230.0,17.462454,58752.0,15.036701,62921.0,16.103695,56629.0,14.493351,41100.0,10.518934,39175.0,10.026259,14146.0,3.620458,160652.0,41.116491,126980.0,32.498644,53321.0,13.646717,20970.0,5.366960,28801.0,7.371188,30620.0,1051.0,0.418598,3947.0,1.572034,4998.0,1.990632,25249.0,10.056318,45147.0,17.981408,47279.0,18.830553,35552.0,14.159856,35142.0,13.996559,12834.0,5.111600,52661.0,20.974127,105564.0,42.044640,47976.0,19.108158,19167.0,7.633944,25708.0,10.239131,904.0,1106.0,1332.0,461.0,327135.0,28586.0,8.738288,39730.0,12.144833,57550.0,17.592126,64231.0,19.634402,26359.0,8.057530,57161.0,17.473214,19709.0,6.024730,19709.0,6.024730,14100.0,4.310147,33809.0,10.334877,344577.0,308407.0,89.503072,274059.0,79.534908,88.862769,34348.0,11.137231,7508.0,2.178903,752.0,0.218239,6945.0,2.015515,17442.0,5.061858,3523.0,1.022413,269078.0,91818.0,123872.0,56680.0,45.756910,145206.0,35138.0,24.198725,39458.0,14.664149,13250.0,9.124967,26208.0,21.157324,34.123191,38.269185,61.730815,33.580009,66.419991,24.212817,177700.0,646910.0,114238.0,17.659025

In [25]:
cols = list(data.columns)
cols

['NAME',
 'GEO_ID',
 'Ed:Population 25+ Educational Attainment',
 'Ed:Less than High School',
 'Ed%:Less than High School',
 'Ed:High School Graduate or Equivalency',
 'Ed%:High School Graduate or Equivalency',
 'Ed:High School Graduate or More',
 'Ed%:High School Graduate or More',
 'Ed:Some College',
 'Ed%:Some College',
 'Ed%:Some College or More',
 'Ed:Associates',
 'Ed%:Associates',
 'Ed:Bachelors',
 'Ed%:Bachelors',
 'Ed:Bachelors or More',
 'Ed%:Bachelors or More',
 'Ed:Masters',
 'Ed:Masters or More',
 'Ed%:Masters or More',
 'Ed%:Masters',
 'Ed:Professional School Degree',
 'Ed%:Professional School Degree',
 'Ed%:Professional School Degree or More',
 'Ed:Doctorate Degree',
 'Ed%:Doctorate Degree',
 'Employment:Armed Forces',
 'Employment:Not in Labor Force',
 'Employment:Employed Civilian',
 'Employment:Unemployed Civilian',
 'Employment%:Civilian Population in LF 16 Over that are Employed',
 'Employment%:Total Civilian Population 16 Over that are Employed',
 'Employment%:Population 16 Over in LF that are Employed',
 'Employment%:Population 16 Over that are Employed Civilians',
 'Employment%:Civilian Population in LF 16 Over that are Unemployed',
 'Employment%:Total Civilian Population 16 Over that are Unemployed',
 'Employment%:Population 16 Over in LF that are Unemployed',
 'Employment%:Population 16 Over that are Unemployed Civilians',
 'Employment%:Civilian Population 16 Over Not in Labor Force',
 'Employment%:Total Population 16 Over Not in Labor Force',
 'Employment:Total Population 16 Over In Labor Force',
 'Employment%:Total Population 16 Over In Labor Force',
 'Employment:Civilian Population 16 Over In Labor Force',
 'Employment%:Civilian Population 16 Over In Labor Force',
 'Employment%:Population 16 Over in LF Employed in Armed Forces',
 'Employment%:Population 16 Over Employed in Armed Forces',
 'HHIncome:Median for Householder Under 25',
 'HHIncome:Median for Householder Under 25 to 44',
 'HHIncome:Median for Householder Under 45 to 64',
 'HHIncome:Median for Householder Under 65 Over',
 'Median Household Income',
 'HHIncome:Total Households',
 'HHIncome:Less than 10,000',
 'HHIncome%:Less than 10,000',
 'HHIncome:10 to 14,999',
 'HHIncome%:10 to 14,999',
 'HHIncome:15 to 19,999',
 'HHIncome%:15 to 19,999',
 'HHIncome:20 to 24,999',
 'HHIncome%:20 to 24,999',
 'HHIncome:25 to 29,999',
 'HHIncome%:25 to 29,999',
 'HHIncome:30 to 34,999',
 'HHIncome:%30 to 34,999',
 'HHIncome:35 to 39,999',
 'HHIncome%:35 to 39,999',
 'HHIncome:40 to 44,999',
 'HHIncome%:40 to 44,999',
 'HHIncome:45 to 49,999',
 'HHIncome%:45 to 49,999',
 'HHIncome:50 to 59,999',
 'HHIncome%:50 to 59,999',
 'HHIncome:60 to 74,999',
 'HHIncome%:60 to 74,999',
 'HHIncome:75 to 99,999',
 'HHIncome%:75 to 99,999',
 'HHIncome:100 to 124,999',
 'HHIncome%:100 to 124,999',
 'HHIncome:125 to 149,999',
 'HHIncome%:125 to 149,999',
 'HHIncome:150 to 199,999',
 'HHIncome%:150 to 199,999',
 'HHIncome:200K or More',
 'HHIncome%:200K or More',
 'Earnings:Less than 5,000',
 'Earnings:% Less than 5,000',
 'Earnings:5,000 to 9,999',
 'Earnings:% 5,000 to 9,999',
 'Earnings:Less than 10,000',
 'Earnings:% Less than 10,000',
 'Earnings:10,000 to 19,999',
 'Earnings:% 10,000 to 19,999',
 'Earnings:20,000 to 29,999',
 'Earnings:% 20,000 to 29,999',
 'Earnings:30,000 to 39,999',
 'Earnings:% 30,000 to 39,999',
 'Earnings:40,000 to 49,999',
 'Earnings:% 40,000 to 49,999',
 'Earnings:50,000 to 64,999',
 'Earnings:% 50,000 to 64,999',
 'Earnings:65,000 to 74,999',
 'Earnings:% 65,000 to 74,999',
 'Earnings:Less than 25,000',
 'Earnings:% Less than 25,000',
 'Earnings:25,000 to 49,999',
 'Earnings:% 25,000 to 49,999',
 'Earnings:50,000 to 74,999',
 'Earnings:% 50,000 to 74,999',
 'Earnings:75,000 to 99,999',
 'Earnings:% 75,000 to 99,999',
 'Earnings:100,000 and Over',
 'Earnings:% 100,000 and Over',
 'Earnings:Median, All Earners',
 'EarningsFT:Less than 5,000',
 'EarningsFT:% Less than 5,000',
 'EarningsFT:5,000 to 9,999',
 'EarningsFT:% 5,000 to 9,999',
 'EarningsFT:Less than 10,000',
 'EarningsFT:% Less than 10,000',
 'EarningsFT:10,000 to 19,999',
 'EarningsFT:% 10,000 to 19,999',
 'EarningsFT:20,000 to 29,999',
 'EarningsFT:% 20,000 to 29,999',
 'EarningsFT:30,000 to 39,999',
 'EarningsFT:% 30,000 to 39,999',
 'EarningsFT:40,000 to 49,999',
 'EarningsFT:% 40,000 to 49,999',
 'EarningsFT:50,000 to 64,999',
 'EarningsFT:% 50,000 to 64,999',
 'EarningsFT:65,000 to 74,999',
 'EarningsFT:% 65,000 to 74,999',
 'EarningsFT:Less than 25,000',
 'EarningsFT:% Less than 25,000',
 'EarningsFT:25,000 to 49,999',
 'EarningsFT:% 25,000 to 49,999',
 'EarningsFT:50,000 to 74,999',
 'EarningsFT:% 50,000 to 74,999',
 'EarningsFT:75,000 to 99,999',
 'EarningsFT:% 75,000 to 99,999',
 'EarningsFT:100,000 and Over',
 'EarningsFT:% 100,000 and Over',
 'Median Gross Rent',
 'Median Monthly Owner Costs',
 'Median Monthly Owner Costs Home with Mortgage',
 'Median Monthly Owner Costs Home without Mortgage',
 'Commute:Workers 16+ Not Working at Home',
 'Commute:Less than 10 Minutes',
 'Commute%:Less than 10 Minutes',
 'Commute:10 to 14 Minutes',
 'Commute%:10 to 14 Minutes',
 'Commute:15 to 19 Minutes',
 'Commute%:15 to 19 Minutes',
 'Commute:20 to 24 Minutes',
 'Commute%:20 to 24 Minutes',
 'Commute:25 to 29 Minutes',
 'Commute%:25 to 29 Minutes',
 'Commute:30 to 34 Minutes',
 'Commute%:30 to 34 Minutes',
 'Commute:35 to 44 Minutes',
 'Commute%:35 to 44 Minutes',
 'Commute:45 to 59 Minutes',
 'Commute%:45 to 59 Minutes',
 'Commute:60 or More Minutes',
 'Commute%:60 or More Minutes',
 'Commute:45 or More Minutes',
 'Commute%:45 or More Minutes',
 'Transpo:Workers Commuting',
 'Transpo:Car, Truck, or Van',
 'Transpo%:Car, Truck, or Van',
 'Transpo:Car, Truck, or Van:Drove Alone',
 'Transpo%:Car, Truck, or Van:Drove Alone',
 'Transpo%:Car, Truck, or Van:Drove Alone Share of Drivers',
 'Transpo:Car, Truck, or Van:Carpooled',
 'Transpo%:Car, Truck, or Van:Carpooled',
 'Transpo:Public Transportation',
 'Transpo%:Public Transportation',
 'Transpo:Bicycle',
 'Transpo%:Bicycle',
 'Transpo:Walk',
 'Transpo%:Walk',
 'Transpo:Worked From Home',
 'Transpo%:Worked From Home',
 'Transpo:Taxi, Motorcycle, Other',
 'Transpo%:Taxi, Motorcycle, Other',
 'CB:Total Housing Units',
 'CB:Cost Burdened Households',
 'CB:Renter Occupied Units',
 'CB:Cost Burdened Renters',
 'CB%:Cost Burdened Renters',
 'CB:Owner Occupied Units',
 'CB:Cost Burdened Homeowners',
 'CB%: Cost Burdened Homeowners',
 'CB:Severe Cost Burdened Households',
 'CB%:Severe Cost Burdened Households',
 'CB:Severe Cost Burdened Homeowners',
 'CB%:Severe Cost Burdened Homeowners',
 'CB:Severe Cost Burdened Renters',
 'CB%:Severe Cost Burdened Renters',
 'CB%:Cost Burdened Households',
 'CB%:Cost Burdened Households Homeowners',
 'CB%:Cost Burdened Households Renters',
 'CB%:Severe Cost Burdened Households Homeowners',
 'CB%:Severe Cost Burdened Households Renters',
 'Average Travel Time to Work',
 'Median Home Value for Owner Occupied Units',
 'Poverty:Population for Whom Poverty Status is Determined',
 'Poverty: Population Below Poverty Level',
 'Poverty%: Below Poverty Level']

In [26]:
conn = sq.connect('../../Outputs/CensusBureau.db')
data.to_sql('CensusBureau_ACS5_2016_CEDS', conn, if_exists = 'replace', index = False)

19